package io.github.okiyashko1337.felicitydashboard;

import android.app.Activity;
import android.app.AlertDialog;
import android.content.Context;
import android.content.Intent;
import android.content.SharedPreferences;
import android.graphics.Color;
import android.graphics.BitmapFactory;
import android.graphics.Canvas;
import android.graphics.Matrix;
import android.graphics.Paint;
import android.graphics.RectF;
import android.graphics.drawable.GradientDrawable;
import android.graphics.drawable.StateListDrawable;
import android.media.AudioAttributes;
import android.media.AudioFormat;
import android.media.AudioTrack;
import android.net.Uri;
import android.os.Bundle;
import android.os.Handler;
import android.os.Looper;
import android.util.Log;
import android.view.Gravity;
import android.view.GestureDetector;
import android.view.MotionEvent;
import android.view.Surface;
import android.view.TextureView;
import android.view.VelocityTracker;
import android.view.View;
import android.view.WindowManager;
import android.widget.Button;
import android.widget.FrameLayout;
import android.widget.GridLayout;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.OverScroller;
import android.widget.TextView;
import java.io.File;
import java.io.FileOutputStream;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Collections;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Locale;
import java.util.Set;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import org.videolan.libvlc.LibVLC;
import org.videolan.libvlc.Media;
import org.videolan.libvlc.MediaPlayer;
import org.videolan.libvlc.interfaces.IMedia;

public final class ArchiveActivity extends Activity {
    private final ExecutorService network=Executors.newCachedThreadPool();
    private final ExecutorService metadataNetwork=Executors.newSingleThreadExecutor();
    private final Handler main=new Handler(Looper.getMainLooper());
    private final ThreeEyeState eventsState=new ThreeEyeState();
    private ThreeEyeClient eventsClient;
    private SharedPreferences prefs;private CameraCatalog.Camera camera;
    private FrameLayout videoContainer;private TextureView surface;private ImageView bestView;private ArchiveOverlay overlay;
    private LibVLC vlc;private MediaPlayer player;private OnvifReplayProxy proxy;private OnvifArchiveSession directSession;private ArchiveMediaDecoder directDecoder;private Surface decoderSurface;private OnvifMetadataSession metadataSession;
    private long syncTime,actualTime,fallbackTime,replayBaseTime,replayClockSourceTime,decodedPlayerAnchorTime,replayStartedAt,playbackAnchorRealtime,playbackAnchorArchiveTime,lastStatsMs,freezeTargetTime,resumeStartTime,activePlaybackEnd,directTarget,pendingPausedSeek=Long.MIN_VALUE,profileLoadedStart=Long.MAX_VALUE,profileLoadedEnd=Long.MIN_VALUE,seekSurfaceFingerprint=Long.MIN_VALUE,seekPlayerTimeAtRtp=Long.MIN_VALUE;private boolean fallbackTried,paused=true,timelineRequested,substream,destroyed,videoLayoutKnown,initialFramePaused,firstFrameScheduled,strictEventTarget,profileLoadRunning,playWhenReady,freezeAtTarget,realtimeSession,staticPausePending,reuseSeekPending,autoAdvancePending,showingBestView=true,pausedSeekInFlight;private int eventLoadAttempts,videoWidth,videoHeight,catalogVideoWidth,catalogVideoHeight,replayRequest,lastPictures,lastReadBytes=-1;private float displayAspect=16f/9f,smoothedFps=-1f,smoothedKbps=-1f,zoom=1f,panX,panY;private String lastCodec="H264";
    private List<ThreeEyeState.Event> archiveEvents=new ArrayList<>();private List<ProfileGClient.SearchEvent> profileEvents=new ArrayList<>();private Button playPause,qualityButton;private TextView streamStats,playbackClock;private String backLabel="‹ LIVE";private float ui=1f;private OverScroller scroller;
    private final Runnable firstFrameTimeout=()->{if((player!=null||directSession!=null)&&bestView.getVisibility()==View.VISIBLE&&!initialFramePaused)replayFailed();};
    private final Runnable dispatchPausedSeek=()->{if(destroyed||pendingPausedSeek==Long.MIN_VALUE)return;long target=pendingPausedSeek;pendingPausedSeek=Long.MIN_VALUE;if(pausedSeekInFlight)Log.i("FelicityReplay","Seek superseded immediately · target="+time(target));pausedSeekInFlight=true;prepareSeek(target);decodeToNearestKeyframe(target,false);};
    private final Runnable timelineTick=new Runnable(){@Override public void run(){if(!initialFramePaused&&proxy!=null&&proxy.replayStartTimeMs()>0){if(seekPlayerTimeAtRtp==Long.MIN_VALUE&&player!=null)seekPlayerTimeAtRtp=Math.max(0,player.getTime());scheduleFirstFrame(40);}if(player!=null&&initialFramePaused&&!paused){updateActualTimeFromPlayer();finishTargetFrameIfReady();advancePlaybackIfNeeded();}fitSurface();updateStreamStats();updatePlaybackClock();if(overlay!=null)overlay.invalidate();main.postDelayed(this,250);}};

    @Override protected void onCreate(Bundle saved){super.onCreate(saved);getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);immersive();prefs=getSharedPreferences("felicity",MODE_PRIVATE);strictEventTarget=getIntent().getBooleanExtra("from_event",false);camera=CameraCatalog.find(prefs,getIntent().getStringExtra("camera"));substream=StreamQuality.useSubstream(this,prefs,camera);backLabel=strictEventTarget?"‹ EVENTS":"‹ LIVE";String requestedBack=getIntent().getStringExtra("back_label");if(requestedBack!=null&&!requestedBack.isEmpty())backLabel=requestedBack;applyQualityDimensions();videoLayoutKnown=true;displayAspect=CameraAspectRepository.get(prefs,camera);CameraAspectRepository.probe(this,prefs,camera);CameraCatalog.select(prefs,camera);EventFilters.apply(eventsState,EventFilters.get(prefs,camera));long explicit=parseUtc(getIntent().getStringExtra("captured_at_utc"));if(explicit>0){syncTime=explicit;ArchiveSession.set(prefs,syncTime,System.currentTimeMillis());}else syncTime=ArchiveSession.validTime(prefs,System.currentTimeMillis());actualTime=syncTime;buildUi();String bestViewPath=getIntent().getStringExtra("best_view_path");android.graphics.Bitmap initial=bestViewPath==null||bestViewPath.isEmpty()?loadPersistedPreview():BitmapFactory.decodeFile(bestViewPath);if(initial!=null){bestView.setImageBitmap(initial);bestView.setVisibility(View.VISIBLE);persistPreview(initial);}if(syncTime>0){overlay.showAdaptive(syncTime,0);setPausedStats();updatePlaybackClock();decodeToNearestKeyframe(syncTime,false);}resolveArchive();}
    @Override protected void onResume(){super.onResume();immersive();if(player==null&&directSession==null&&playPause!=null){paused=true;playPause.setText("▶");playPause.setEnabled(true);setPausedStats();updatePlaybackClock();}}
    @Override protected void onStop(){if(player!=null||directSession!=null){updateActualTimeFromPlayer();holdCurrentFrame();syncTime=actualTime;resumeStartTime=actualTime;paused=true;replayRequest++;reuseSeekPending=false;firstFrameScheduled=false;if(playPause!=null){playPause.setText("▶");playPause.setEnabled(true);}stopReplay(false);}super.onStop();}
    private void immersive(){DeviceUi.apply(this);}

    private void buildUi(){ui=Math.min(getResources().getDisplayMetrics().widthPixels/960f,getResources().getDisplayMetrics().heightPixels/480f);FrameLayout root=new FrameLayout(this);root.setBackgroundColor(Color.BLACK);videoContainer=new FrameLayout(this);FrameLayout.LayoutParams video=new FrameLayout.LayoutParams(-1,-1);video.topMargin=u(64);video.bottomMargin=u(80);root.addView(videoContainer,video);surface=new TextureView(this);surface.setOpaque(false);surface.setAlpha(.01f);videoContainer.addView(surface,new FrameLayout.LayoutParams(-1,-1,Gravity.CENTER));bestView=new ImageView(this);bestView.setScaleType(ImageView.ScaleType.FIT_XY);bestView.setBackgroundColor(Color.BLACK);videoContainer.addView(bestView,new FrameLayout.LayoutParams(-1,-1,Gravity.CENTER));CameraOrientation.apply(videoContainer,surface,camera);scroller=new OverScroller(this);overlay=new ArchiveOverlay(this);root.addView(overlay,new FrameLayout.LayoutParams(-1,-1));
        Button back=button(backLabel);back.setTextSize(12*ui);FrameLayout.LayoutParams backParams=new FrameLayout.LayoutParams(u(118),u(48),Gravity.TOP|Gravity.LEFT);backParams.setMargins(u(8),u(8),0,0);root.addView(back,backParams);back.setOnClickListener(v->finish());
        Button cameraButton=button(camera.name);cameraButton.setTextSize(11*ui);FrameLayout.LayoutParams cameraParams=new FrameLayout.LayoutParams(u(144),u(48),Gravity.TOP|Gravity.LEFT);cameraParams.setMargins(u(132),u(8),0,0);root.addView(cameraButton,cameraParams);cameraButton.setOnClickListener(v->pickCamera());
        streamStats=new TextView(this);streamStats.setText("CONNECTING…");streamStats.setTextColor(Color.WHITE);streamStats.setTextSize(10*ui);streamStats.setGravity(Gravity.CENTER);streamStats.setTypeface(android.graphics.Typeface.DEFAULT_BOLD);streamStats.setLines(2);FrameLayout.LayoutParams statsParams=new FrameLayout.LayoutParams(u(174),u(58),Gravity.TOP|Gravity.LEFT);statsParams.setMargins(u(278),u(3),0,0);root.addView(streamStats,statsParams);
        playbackClock=new TextView(this);playbackClock.setTextColor(Color.WHITE);playbackClock.setTextSize(12*ui);playbackClock.setGravity(Gravity.CENTER);playbackClock.setTypeface(android.graphics.Typeface.DEFAULT_BOLD);playbackClock.setLines(2);FrameLayout.LayoutParams playbackParams=new FrameLayout.LayoutParams(u(270),u(58),Gravity.TOP|Gravity.LEFT);playbackParams.setMargins(u(462),u(3),0,0);root.addView(playbackClock,playbackParams);
        qualityButton=button(substream?"LQ":"HQ");qualityButton.setTextSize(11*ui);qualityButton.setContentDescription("Toggle stream quality");FrameLayout.LayoutParams qualityParams=new FrameLayout.LayoutParams(u(64),u(48),Gravity.TOP|Gravity.LEFT);qualityParams.setMargins(u(738),u(8),0,0);root.addView(qualityButton,qualityParams);qualityButton.setOnClickListener(v->toggleQuality());
        playPause=control("▶",21);addControl(root,playPause,12,58);playPause.setContentDescription("Play archive");playPause.setOnClickListener(v->togglePlayback());
        Button previous=control("‹  PREV",11);addControl(root,previous,78,88);previous.setContentDescription("Previous recording");previous.setOnClickListener(v->jumpEvent(-1));
        Button next=control("NEXT  ›",11);addControl(root,next,174,88);next.setContentDescription("Next recording");next.setOnClickListener(v->jumpEvent(1));
        Button calendar=control("▦  DATE",11);addControl(root,calendar,270,96);calendar.setContentDescription("Recording calendar");calendar.setOnClickListener(v->showCalendar());setContentView(root);main.post(timelineTick);}

    private int u(float value){return Math.round(value*ui);}
    private Button button(String text){Button button=new Button(this);button.setText(text);button.setTextColor(Color.WHITE);button.setTextSize(18*ui);ControlStyle.apply(button,false);return button;}
    private Button control(String text,float size){Button b=button(text);b.setTextSize(size*ui);b.setTypeface(android.graphics.Typeface.DEFAULT_BOLD);b.setPadding(u(4),0,u(4),u(1));b.setBackground(controlBackground());return b;}
    private android.graphics.drawable.Drawable controlShape(int fill,int stroke){GradientDrawable shape=new GradientDrawable();shape.setShape(GradientDrawable.RECTANGLE);shape.setColor(fill);shape.setCornerRadius(11);shape.setStroke(1,stroke);return shape;}
    private StateListDrawable controlBackground(){StateListDrawable states=new StateListDrawable();states.addState(new int[]{android.R.attr.state_pressed},controlShape(0xff168b7d,0xff43e0cc));states.addState(new int[]{android.R.attr.state_focused},controlShape(0xff176b61,0xff43e0cc));states.addState(new int[]{},controlShape(0xee303836,0xff55716c));return states;}
    private void addControl(FrameLayout root,Button b,int left,int width){FrameLayout.LayoutParams p=new FrameLayout.LayoutParams(u(width),u(48),Gravity.BOTTOM|Gravity.LEFT);p.setMargins(u(left),0,0,u(84));root.addView(b,p);}

    private void resolveArchive(){
        overlay.status="LOADING EVENTS";overlay.invalidate();eventsState.camera=camera.name;eventsState.limit=200;eventsState.loadThumbnails=false;eventsClient=new ThreeEyeClient(eventsState);eventsClient.configure(prefs.getString("threeeye_base_url",eventsState.baseUrl),prefs.getString("threeeye_user",""),prefs.getString("threeeye_password",""));
        network.execute(()->eventsClient.load((ok,error)->{List<ThreeEyeState.Event> events=ok?withoutMotion(eventsState.snapshot()):new ArrayList<>();archiveEvents=events;if(syncTime<=0)syncTime=events.isEmpty()?System.currentTimeMillis()-5000:parseUtc(events.get(0).capturedAt);ArchiveSession.set(prefs,syncTime,System.currentTimeMillis());ThreeEyeState.Event nearest=nearest(events,syncTime);fallbackTime=nearest==null?syncTime:parseUtc(nearest.capturedAt);loadBestViewIfNeeded(nearest);long target=syncTime;main.post(()->{timelineRequested=true;if(player==null&&!freezeAtTarget){paused=true;actualTime=target;bestView.setVisibility(View.VISIBLE);playPause.setText("▶");}if(!paused)activePlaybackEnd=playbackEndFor(actualTime);overlay.status="";overlay.showAdaptive(actualTime>0?actualTime:target,eventCountOnDay(events,target));ensureProfileTimeline(overlay.visibleStart(),overlay.visibleEnd());updatePlaybackClock();if(strictEventTarget&&player==null&&!freezeAtTarget)decodeToNearestKeyframe(target,false);});}));
    }
    private void loadBestViewIfNeeded(ThreeEyeState.Event event){if(event==null||bestView.getDrawable()!=null)return;eventsClient.loadSelectedImage(event,(ok,error)->{if(ok&&event.image!=null)main.post(()->{if(player==null||freezeAtTarget){showingBestView=true;bestView.setImageBitmap(event.image);bestView.setVisibility(View.VISIBLE);persistPreview(event.image);setPausedStats();overlay.invalidate();}});});}
    private void ensureProfileTimeline(long visibleStart,long visibleEnd){
        long span=Math.max(ArchiveTimeline.HOUR,visibleEnd-visibleStart),margin=Math.max(ArchiveTimeline.HOUR,span/2),wantedStart=ArchiveTimeline.dayStart(visibleStart-margin),wantedEnd=ArchiveTimeline.dayStart(visibleEnd+margin)+ArchiveTimeline.DAY;
        synchronized(profileEvents){if(profileLoadRunning)return;if(profileLoadedStart==Long.MAX_VALUE){profileLoadRunning=true;requestProfileTimeline(wantedStart,wantedEnd);return;}if(wantedStart<profileLoadedStart){profileLoadRunning=true;requestProfileTimeline(wantedStart,profileLoadedStart);return;}if(wantedEnd>profileLoadedEnd){profileLoadRunning=true;requestProfileTimeline(profileLoadedEnd,wantedEnd);}}
    }
    private void requestProfileTimeline(long start,long end){metadataNetwork.execute(()->{try{List<ProfileGClient.SearchEvent> loaded=ProfileGRepository.events(prefs,camera.name,start,end,substream);synchronized(profileEvents){for(ProfileGClient.SearchEvent candidate:loaded){boolean duplicate=false;for(ProfileGClient.SearchEvent existing:profileEvents)if(existing.time==candidate.time&&existing.type.equals(candidate.type)){duplicate=true;break;}if(!duplicate)profileEvents.add(candidate);}Collections.sort(profileEvents,(left,right)->Long.compare(left.time,right.time));profileLoadedStart=Math.min(profileLoadedStart,start);profileLoadedEnd=Math.max(profileLoadedEnd,end);profileLoadRunning=false;}main.post(()->{if(!paused)activePlaybackEnd=playbackEndFor(actualTime);overlay.invalidate();ensureProfileTimeline(overlay.visibleStart(),overlay.visibleEnd());});}catch(Exception profileError){synchronized(profileEvents){profileLoadRunning=false;}Log.w("FelicityProfileG","Timeline metadata · "+profileError.getMessage());}});}

    private void startReplay(long time){startReplay(time,false);}
    private void startRealtime(long time){freezeAtTarget=false;playWhenReady=true;autoAdvancePending=false;activePlaybackEnd=playbackEndFor(time);holdCurrentFrame();startReplay(time,true);}
    private void startReplay(long time,boolean realtime){
        if(reuseReplay(time,realtime))return;
        if(destroyed||network.isShutdown())return;if(player!=null){updateActualTimeFromPlayer();try{player.pause();}catch(Exception ignored){}}stopReplay(false);int request=++replayRequest;replayStartedAt=android.os.SystemClock.elapsedRealtime();playbackAnchorRealtime=0;playbackAnchorArchiveTime=actualTime;replayBaseTime=time;replayClockSourceTime=0;decodedPlayerAnchorTime=-1;initialFramePaused=false;firstFrameScheduled=false;seekSurfaceFingerprint=Long.MIN_VALUE;seekPlayerTimeAtRtp=Long.MIN_VALUE;lastStatsMs=0;lastReadBytes=-1;lastPictures=0;smoothedFps=-1;smoothedKbps=-1;Log.i("FelicityReplay","Seek requested · "+camera.name+" · "+time(time));bestView.setVisibility(View.VISIBLE);paused=true;if(playPause!=null){playPause.setText(realtime?"Ⅱ":"▶");playPause.setEnabled(false);}overlay.status="SEEKING · "+time(time);overlay.invalidate();
        network.execute(()->{try{ProfileGRepository.Replay replay=ProfileGRepository.replay(prefs,camera.name,substream);main.post(()->{if(!destroyed&&request==replayRequest)startDirectPlayer(replay,time,realtime,request);});}catch(Exception error){main.post(()->{if(!destroyed&&request==replayRequest)showError(error.getMessage());});}});
    }

    private void acceptOnvifFigure(OnvifMetadataDecoder.Figure figure){long at=parseUtc(figure.utc);String type=figure.type();if(at<=0||type.isEmpty())return;main.post(()->{synchronized(profileEvents){for(ProfileGClient.SearchEvent existing:profileEvents)if(existing.time==at&&existing.type.equals(type))return;profileEvents.add(new ProfileGClient.SearchEvent(at,type));Collections.sort(profileEvents,(left,right)->Long.compare(left.time,right.time));}if(overlay!=null)overlay.invalidate();});}

    private void startDirectPlayer(ProfileGRepository.Replay replay,long time,boolean realtime,int request){
        stopReplay(false);if(!surface.isAvailable()){main.postDelayed(()->{if(!destroyed&&request==replayRequest)startDirectPlayer(replay,time,realtime,request);},100);return;}directTarget=time;realtimeSession=realtime;decoderSurface=new Surface(surface.getSurfaceTexture());
        directSession=new OnvifArchiveSession(replay.uri,replay.user,replay.password,time,new OnvifArchiveSession.Listener(){
            @Override public void onConfigured(boolean hevc,List<byte[]> csd){try{directDecoder=new ArchiveMediaDecoder(hevc,videoWidth,videoHeight,csd,decoderSurface,main,new ArchiveMediaDecoder.Listener(){@Override public void onFrame(long at){acceptDirectFrame(request,at);}@Override public void onFormat(int width,int height,String codec){main.post(()->{if(width>0&&height>0){videoWidth=width;videoHeight=height;}lastCodec=codec;});}@Override public void onError(Exception error){main.post(()->{if(request==replayRequest)replayFailed();});}});}catch(Exception error){main.post(()->{if(request==replayRequest)showError("Decoder: "+error.getMessage());});}}
            @Override public void onAccessUnit(byte[] data,long at,long rtp,boolean keyframe){ArchiveMediaDecoder decoder=directDecoder;if(decoder!=null)decoder.queue(data,at,keyframe);}
            @Override public void onError(Exception error){main.post(()->{if(!destroyed&&request==replayRequest){Log.w("FelicityReplay","Direct archive · "+error.getMessage());replayFailed();}});}
        });directSession.start();main.removeCallbacks(firstFrameTimeout);main.postDelayed(firstFrameTimeout,12000);
    }
    private boolean reuseDirectReplay(long time,boolean realtime){if(destroyed||directSession==null||directDecoder==null)return false;main.removeCallbacks(firstFrameTimeout);int request=++replayRequest;replayStartedAt=android.os.SystemClock.elapsedRealtime();directTarget=time;replayBaseTime=time;initialFramePaused=false;reuseSeekPending=true;freezeAtTarget=!realtime;playWhenReady=realtime;realtimeSession=realtime;playbackAnchorRealtime=0;bestView.setVisibility(View.VISIBLE);bestView.bringToFront();surface.setAlpha(.01f);paused=true;playPause.setText(realtime?"Ⅱ":"▶");playPause.setEnabled(false);overlay.status="SEEKING · "+time(time);overlay.invalidate();directDecoder.seek();directSession.seek(time);Log.i("FelicityReplay","Direct seek · "+camera.name+" · "+time(time));main.postDelayed(firstFrameTimeout,8000);return true;}
    private void acceptDirectFrame(int creationRequest,long at){main.post(()->{if(destroyed||directSession==null||at<=0)return;if(!initialFramePaused){main.removeCallbacks(firstFrameTimeout);reuseSeekPending=false;initialFramePaused=true;actualTime=at;replayClockSourceTime=at;Log.i("FelicityReplay","Direct first frame · "+camera.name+" · "+(android.os.SystemClock.elapsedRealtime()-replayStartedAt)+" ms · requested="+time(directTarget)+" · actual="+time(at));if(freezeAtTarget){paused=true;playbackAnchorArchiveTime=at;playbackAnchorRealtime=0;finishTargetFrameIfReady();}else{paused=false;playWhenReady=false;showingBestView=false;playbackAnchorArchiveTime=at;playbackAnchorRealtime=android.os.SystemClock.elapsedRealtime();playPause.setText("Ⅱ");playPause.setEnabled(true);main.postDelayed(()->revealSurface(replayRequest),40);}overlay.status="";updatePlaybackClock();overlay.invalidate();return;}if(!paused){actualTime=at;playbackAnchorArchiveTime=at;playbackAnchorRealtime=android.os.SystemClock.elapsedRealtime();advancePlaybackIfNeeded();updatePlaybackClock();overlay.invalidate();}});}

    private void startPlayer(OnvifReplayProxy next,String uri,boolean realtime){
        stopReplay(false);proxy=next;realtimeSession=realtime;int caching=100;ArrayList<String> options=new ArrayList<>();options.add("--rtsp-tcp");options.add("--network-caching="+caching);options.add("--live-caching="+caching);options.add("--clock-jitter=0");options.add("--clock-synchro=0");options.add("--drop-late-frames");options.add("--skip-frames");if(vlc==null)vlc=new LibVLC(this,options);player=new MediaPlayer(vlc);player.setUseOrientationFromBounds(false);player.setVideoScale(MediaPlayer.ScaleType.SURFACE_BEST_FIT);player.getVLCVout().setVideoView(surface);
        player.getVLCVout().attachViews((vout,width,height,visibleWidth,visibleHeight,sarNum,sarDen)->runOnUiThread(()->{if(catalogVideoWidth<=0&&visibleWidth>0&&visibleHeight>0){videoWidth=visibleWidth;videoHeight=visibleHeight;}Log.i("FelicityReplay","Video layout · coded="+width+"×"+height+" · visible="+visibleWidth+"×"+visibleHeight+" · catalog="+catalogVideoWidth+"×"+catalogVideoHeight);fitSurface();}));
        player.setEventListener(event->{
            if(event.type==MediaPlayer.Event.Vout&&event.getVoutCount()>0)runOnUiThread(()->scheduleFirstFrame(350));
            else if(event.type==MediaPlayer.Event.TimeChanged&&reuseSeekPending){/* Wait for the first RTP packet from the new seek generation. */}
            else if(event.type==MediaPlayer.Event.EncounteredError||event.type==MediaPlayer.Event.EndReached)runOnUiThread(()->{if(!paused&&initialFramePaused){if(!advanceToNextAi())replayFailed();}else if(!paused||!initialFramePaused)replayFailed();});
        });
        Media media=new Media(vlc,Uri.parse(uri));media.setHWDecoderEnabled(true,false);media.addOption(":rtsp-tcp");media.addOption(":network-caching="+caching);media.addOption(":live-caching="+caching);media.addOption(":clock-jitter=0");media.addOption(":clock-synchro=0");player.setMedia(media);media.release();player.play();main.removeCallbacks(firstFrameTimeout);main.postDelayed(firstFrameTimeout,12000);
    }

    private boolean reuseReplay(long time,boolean realtime){if(directSession!=null&&directDecoder!=null)return reuseDirectReplay(time,realtime);if(destroyed||player==null||proxy==null||network.isShutdown())return false;main.removeCallbacks(firstFrameTimeout);int request=++replayRequest;replayStartedAt=android.os.SystemClock.elapsedRealtime();replayBaseTime=time;replayClockSourceTime=0;decodedPlayerAnchorTime=-1;initialFramePaused=false;firstFrameScheduled=false;seekSurfaceFingerprint=Long.MIN_VALUE;seekPlayerTimeAtRtp=Long.MIN_VALUE;reuseSeekPending=true;freezeAtTarget=!realtime;playWhenReady=realtime;realtimeSession=realtime;playbackAnchorRealtime=0;playbackAnchorArchiveTime=actualTime;lastStatsMs=0;lastReadBytes=-1;lastPictures=0;smoothedFps=smoothedKbps=-1f;Log.i("FelicityReplay","Seek reused · "+camera.name+" · "+time(time));bestView.setVisibility(View.VISIBLE);bestView.bringToFront();surface.setAlpha(.01f);paused=true;playPause.setText(realtime?"Ⅱ":"▶");playPause.setEnabled(false);overlay.status="SEEKING · "+time(time);overlay.invalidate();OnvifReplayProxy active=proxy;network.execute(()->{boolean accepted=active.seek(time,true,false);main.post(()->{if(destroyed||request!=replayRequest)return;if(!accepted){reuseSeekPending=false;stopReplay(false);startReplay(time,realtime);return;}try{player.play();Log.i("FelicityReplay","VLC session resumed for injected seek · state="+player.getPlayerState());main.removeCallbacks(firstFrameTimeout);main.postDelayed(firstFrameTimeout,5000);}catch(Exception error){Log.w("FelicityReplay","Session seek failed · "+error.getMessage());reuseSeekPending=false;stopReplay(false);startReplay(time,realtime);}});});return true;}

    private void scheduleFirstFrame(long delayMs){if(initialFramePaused||firstFrameScheduled||proxy==null||proxy.replayStartTimeMs()<=0)return;long fingerprint=surfaceFingerprint();if(fingerprint==Long.MIN_VALUE)return;if(seekSurfaceFingerprint==Long.MIN_VALUE){seekSurfaceFingerprint=fingerprint;return;}if(fingerprint==seekSurfaceFingerprint)return;firstFrameScheduled=true;int request=replayRequest;main.postDelayed(()->{firstFrameScheduled=false;if(request==replayRequest&&!destroyed&&surfaceFingerprint()!=seekSurfaceFingerprint)acceptReplayFrame();},delayMs);}

    private long surfaceFingerprint(){if(surface==null||!surface.isAvailable())return Long.MIN_VALUE;android.graphics.Bitmap sample=null;try{sample=surface.getBitmap(24,14);if(sample==null)return Long.MIN_VALUE;long hash=0xcbf29ce484222325L;for(int y=0;y<sample.getHeight();y++)for(int x=0;x<sample.getWidth();x++){hash^=sample.getPixel(x,y);hash*=0x100000001b3L;}return hash;}catch(Exception ignored){return Long.MIN_VALUE;}finally{if(sample!=null)sample.recycle();}}

    private void acceptReplayFrame(){if(initialFramePaused||player==null)return;main.removeCallbacks(firstFrameTimeout);reuseSeekPending=false;initialFramePaused=true;Log.i("FelicityReplay","First frame · "+camera.name+" · "+(android.os.SystemClock.elapsedRealtime()-replayStartedAt)+" ms");updateActualTimeFromPlayer();if(freezeAtTarget){paused=true;playbackAnchorArchiveTime=actualTime;playbackAnchorRealtime=0;finishTargetFrameIfReady();}else if(playWhenReady){paused=false;playWhenReady=false;showingBestView=false;playbackAnchorArchiveTime=actualTime;playbackAnchorRealtime=android.os.SystemClock.elapsedRealtime();playPause.setText("Ⅱ");main.postDelayed(()->revealSurface(replayRequest),50);}else{paused=true;playbackAnchorArchiveTime=actualTime;playbackAnchorRealtime=0;playPause.setText("▶");}playPause.setEnabled(true);fitSurface();overlay.status="";updatePlaybackClock();overlay.invalidate();}
    private void pauseReplayTransport(){OnvifArchiveSession direct=directSession;if(direct!=null){direct.pause();return;}OnvifReplayProxy active=proxy;if(active!=null&&!network.isShutdown())network.execute(active::pause);}

    private void updateActualTimeFromPlayer(){
        if(player==null)return;
        if(replayClockSourceTime==0){long resolved=proxy==null?0:proxy.replayStartTimeMs();if(resolved>0){long requestedBase=replayBaseTime;decodedPlayerAnchorTime=Math.max(0,player.getTime());long playerAtRtp=seekPlayerTimeAtRtp==Long.MIN_VALUE?decodedPlayerAnchorTime:seekPlayerTimeAtRtp,decodedDelta=Math.max(0,decodedPlayerAnchorTime-playerAtRtp);if(decodedDelta>30_000)decodedDelta=0;actualTime=resolved+decodedDelta;replayClockSourceTime=actualTime;replayBaseTime=resolved;playbackAnchorArchiveTime=actualTime;playbackAnchorRealtime=android.os.SystemClock.elapsedRealtime();Log.i("FelicityReplay","Decoded playhead anchored · requested="+time(requestedBase)+" · actual="+time(actualTime)+" · rtp="+time(resolved)+" · playerDelta="+decodedDelta);if(overlay!=null)overlay.reveal(actualTime);}return;}
        if(!paused&&decodedPlayerAnchorTime>=0){long playerTime=player.getTime(),delta=playerTime-decodedPlayerAnchorTime;if(delta>=0&&delta<ArchiveTimeline.DAY)actualTime=replayClockSourceTime+delta;else if(playbackAnchorRealtime>0)actualTime=playbackAnchorArchiveTime+android.os.SystemClock.elapsedRealtime()-playbackAnchorRealtime;return;}
        if(!paused&&playbackAnchorRealtime>0)actualTime=playbackAnchorArchiveTime+android.os.SystemClock.elapsedRealtime()-playbackAnchorRealtime;
    }

    private long playbackEndFor(long target){ProfileGClient.SearchEvent selected=null;long distance=Long.MAX_VALUE;synchronized(profileEvents){for(ProfileGClient.SearchEvent event:profileEvents){if(isMotion(event.type)||event.endTime<=event.time)continue;if(target>=event.time-10_000&&target<=event.endTime){selected=event;break;}long next=Math.abs(event.time-target);if(next<distance){distance=next;selected=event;}}}return selected!=null&&(distance<=120_000||target>=selected.time-10_000&&target<=selected.endTime)?selected.endTime:target+15_000;}
    private void advancePlaybackIfNeeded(){if(!paused&&!autoAdvancePending&&activePlaybackEnd>0&&actualTime>=activePlaybackEnd)advanceToNextAi();}
    private boolean advanceToNextAi(){if(autoAdvancePending)return true;long reference=Math.max(actualTime,activePlaybackEnd),next=Long.MAX_VALUE;synchronized(profileEvents){for(ProfileGClient.SearchEvent event:profileEvents){if(isMotion(event.type))continue;if(event.time>reference+500&&event.time<next)next=event.time;}}if(next==Long.MAX_VALUE){paused=true;activePlaybackEnd=0;playPause.setText("▶");setPausedStats();return false;}autoAdvancePending=true;Log.i("FelicityReplay","AI segment complete · next="+time(next));startRealtime(next);return true;}

    private void decodeToNearestKeyframe(long target,boolean autoplay){freezeTargetTime=target;resumeStartTime=target;freezeAtTarget=true;playWhenReady=autoplay;holdCurrentFrame();overlay.status="SEEKING  "+time(target);startReplay(target,false);}
    private void finishTargetFrameIfReady(){if(!freezeAtTarget||staticPausePending||!initialFramePaused||((player==null||proxy==null)&&(directDecoder==null||directSession==null)))return;long frameTime=actualTime>0?actualTime:freezeTargetTime;boolean autoplay=playWhenReady;int request=replayRequest;staticPausePending=true;Log.i("FelicityReplay","Decoded keyframe ready · requested="+time(freezeTargetTime)+" · frame="+time(frameTime)+" · autoplay="+autoplay);main.postDelayed(()->{staticPausePending=false;if(request==replayRequest&&freezeAtTarget&&!destroyed)showDecodedPause(frameTime,autoplay);},100);}
    private void showDecodedPause(long frameTime,boolean autoplay){if(pendingPausedSeek!=Long.MIN_VALUE){Log.i("FelicityReplay","Decoded superseded frame discarded · frame="+time(frameTime)+" · pending="+time(pendingPausedSeek));freezeAtTarget=false;pausedSeekInFlight=false;main.removeCallbacks(dispatchPausedSeek);main.post(dispatchPausedSeek);return;}updateCodecFromPlayer();freezeAtTarget=false;playWhenReady=false;paused=true;showingBestView=false;syncTime=actualTime=frameTime;resumeStartTime=frameTime;playbackAnchorArchiveTime=frameTime;playbackAnchorRealtime=0;ArchiveSession.set(prefs,frameTime,System.currentTimeMillis());playPause.setText("▶");playPause.setEnabled(true);overlay.status="";setPausedStats();updatePlaybackClock();overlay.invalidate();int request=replayRequest;main.postDelayed(()->freezeDecodedFrame(request,frameTime,autoplay),180);}
    private void freezeDecodedFrame(int request,long frameTime,boolean autoplay){if(destroyed||request!=replayRequest||!paused)return;if(pendingPausedSeek!=Long.MIN_VALUE){Log.i("FelicityReplay","Captured frame superseded · pending="+time(pendingPausedSeek));pausedSeekInFlight=false;main.removeCallbacks(dispatchPausedSeek);main.post(dispatchPausedSeek);return;}android.graphics.Bitmap frame=null;try{frame=surface.getBitmap();}catch(Exception ignored){}if(isUsablePreview(frame)){bestView.setImageBitmap(frame);persistPreview(frame);}bestView.setVisibility(View.VISIBLE);bestView.bringToFront();surface.setAlpha(.01f);pauseReplayTransport();pausedSeekInFlight=false;if(autoplay&&!destroyed)startRealtime(frameTime);}
    private void enterStaticPause(long frameTime,boolean autoplay){updateCodecFromPlayer();showingBestView=false;freezeAtTarget=false;playWhenReady=false;paused=true;syncTime=actualTime=frameTime;resumeStartTime=frameTime;playbackAnchorArchiveTime=frameTime;playbackAnchorRealtime=0;ArchiveSession.set(prefs,frameTime,System.currentTimeMillis());playPause.setText("▶");playPause.setEnabled(true);overlay.status="";setPausedStats();updatePlaybackClock();overlay.invalidate();pauseReplayTransport();int request=replayRequest;main.postDelayed(()->{if(request!=replayRequest||destroyed||!paused)return;try{android.graphics.Bitmap frame=surface.getBitmap();if(isUsablePreview(frame)){bestView.setImageBitmap(frame);persistPreview(frame);}}catch(Exception ignored){}bestView.setVisibility(View.VISIBLE);bestView.bringToFront();surface.setAlpha(.01f);if(autoplay&&!destroyed)startRealtime(resumeStartTime);},100);}
    private void holdCurrentFrame(){try{if(surface.getAlpha()>.5f){android.graphics.Bitmap frame=surface.getBitmap();if(isUsablePreview(frame)){bestView.setImageBitmap(frame);persistPreview(frame);}}}catch(Exception ignored){}bestView.setVisibility(View.VISIBLE);bestView.bringToFront();surface.setAlpha(.01f);}
    private File previewFile(){return new File(getFilesDir(),"archive-preview-"+camera.id+".jpg");}
    private android.graphics.Bitmap loadPersistedPreview(){File archive=previewFile(),live=new File(getFilesDir(),"camera-preview-"+camera.id+".jpg");android.graphics.Bitmap cached=archive.isFile()?BitmapFactory.decodeFile(archive.getAbsolutePath()):null;if(isUsablePreview(cached))return cached;return live.isFile()?BitmapFactory.decodeFile(live.getAbsolutePath()):null;}
    private void persistPreview(android.graphics.Bitmap bitmap){if(!isUsablePreview(bitmap)||network.isShutdown())return;try{network.execute(()->{synchronized(ArchiveActivity.this){File target=previewFile(),temporary=new File(target.getAbsolutePath()+".tmp");try(FileOutputStream output=new FileOutputStream(temporary)){bitmap.compress(android.graphics.Bitmap.CompressFormat.JPEG,88,output);output.flush();if(!temporary.renameTo(target)){try(FileOutputStream fallback=new FileOutputStream(target)){bitmap.compress(android.graphics.Bitmap.CompressFormat.JPEG,88,fallback);}temporary.delete();}}catch(Exception error){temporary.delete();Log.w("FelicityReplay","Preview JPEG cache · "+error.getClass().getSimpleName());}}});}catch(Exception ignored){}}
    private static boolean isUsablePreview(android.graphics.Bitmap bitmap){if(bitmap==null||bitmap.getWidth()<2||bitmap.getHeight()<2)return false;int lit=0,total=0;for(int y=0;y<8;y++)for(int x=0;x<12;x++){int color=bitmap.getPixel((x*2+1)*bitmap.getWidth()/24,(y*2+1)*bitmap.getHeight()/16),sum=Color.red(color)+Color.green(color)+Color.blue(color);if(sum>18)lit++;total++;}return lit>=Math.max(2,total/25);}
    private void revealSurface(int request){if(request!=replayRequest||destroyed)return;surface.bringToFront();surface.setAlpha(1f);}
    private void updateCodecFromPlayer(){if(player==null)return;IMedia.VideoTrack track=player.getCurrentVideoTrack();if(track==null||track.codec==null)return;String raw=track.codec.toUpperCase(Locale.US);lastCodec=raw.contains("H265")||raw.contains("HEVC")?"H265":raw.contains("H264")||raw.contains("AVC")?"H264":raw.length()>8?raw.substring(0,8):raw;}

    private void fitSurface(){if(videoContainer==null||surface==null)return;displayAspect=CameraAspectRepository.get(prefs,camera);int cw=videoContainer.getWidth(),ch=videoContainer.getHeight();if(cw<1||ch<1)return;float playerAspect=CameraCatalog.playerAspect(camera);if(player!=null){surface.setTransform(null);player.setVideoScale(MediaPlayer.ScaleType.SURFACE_BEST_FIT);player.setAspectRatio(Math.max(1,Math.round(playerAspect*1000))+":1000");player.setScale(0);player.getVLCVout().setWindowSize(cw,ch);}else{int width=surface.getWidth(),height=surface.getHeight();if(width>0&&height>0){float[] fit=CameraCatalog.textureFit(playerAspect,width,height);Matrix transform=new Matrix();transform.setScale(fit[0],fit[1],width/2f,height/2f);surface.setTransform(transform);}}applyVideoTransform(bestView);}

    private void applyQualityDimensions(){int[] fallback=CameraCatalog.fallbackVideoSize(camera,substream);catalogVideoWidth=substream&&camera.subWidth>0?camera.subWidth:camera.mainWidth;catalogVideoHeight=substream&&camera.subHeight>0?camera.subHeight:camera.mainHeight;videoWidth=catalogVideoWidth>0?catalogVideoWidth:fallback[0];videoHeight=catalogVideoHeight>0?catalogVideoHeight:fallback[1];}
    private void toggleQuality(){long target=actualTime>0?actualTime:syncTime;boolean autoplay=!paused;substream=!substream;StreamQuality.select(prefs,camera,substream);qualityButton.setText(substream?"LQ":"HQ");applyQualityDimensions();lastStatsMs=0;lastPictures=0;lastReadBytes=-1;smoothedFps=smoothedKbps=-1f;zoom=1f;panX=panY=0;applyVideoZoom();synchronized(profileEvents){profileEvents.clear();profileLoadedStart=Long.MAX_VALUE;profileLoadedEnd=Long.MIN_VALUE;profileLoadRunning=false;}if(autoplay)startRealtime(target);else setPausedStats();ensureProfileTimeline(overlay.visibleStart(),overlay.visibleEnd());}
    private void zoomAt(float focusX,float focusY,float next){float old=zoom,ratio=next/old,cx=videoContainer.getWidth()/2f,cy=videoContainer.getHeight()/2f;panX=ratio*panX+(1-ratio)*(focusX-cx);panY=ratio*panY+(1-ratio)*(focusY-cy);zoom=next;if(zoom<=1.001f){zoom=1f;panX=panY=0;}applyVideoZoom();}
    private float[] panBounds(){float vw=videoContainer.getWidth(),vh=videoContainer.getHeight(),videoAspect=displayAspect,viewAspect=vw/Math.max(1f,vh),baseW,baseH;if(videoAspect>viewAspect){baseW=vw;baseH=vw/videoAspect;}else{baseH=vh;baseW=vh*videoAspect;}return new float[]{Math.max(0,(baseW*zoom-vw)/2f),Math.max(0,(baseH*zoom-vh)/2f)};}
    private void applyVideoZoom(){if(videoContainer==null)return;if(zoom<=1.001f)fitSurface();float[] bounds=panBounds();panX=Math.max(-bounds[0],Math.min(bounds[0],panX));panY=Math.max(-bounds[1],Math.min(bounds[1],panY));applyVideoTransform(surface);applyVideoTransform(bestView);}
    private void applyVideoTransform(View view){if(view==null)return;float baseX=1f,baseY=1f;if(view==bestView&&view.getWidth()>0&&view.getHeight()>0){float[] fit=CameraCatalog.textureFit(CameraCatalog.playerAspect(camera),view.getWidth(),view.getHeight());baseX=fit[0];baseY=fit[1];}view.setPivotX(view.getWidth()/2f);view.setPivotY(view.getHeight()/2f);view.setScaleX(baseX*zoom);view.setScaleY(baseY*zoom);view.setTranslationX(panX);view.setTranslationY(panY);}
    private void continueFling(){if(scroller!=null&&scroller.computeScrollOffset()){panX=scroller.getCurrX();panY=scroller.getCurrY();applyVideoZoom();overlay.postOnAnimation(this::continueFling);}}
    private void playTimelineClick(){final int rate=16000,count=400;short[] pcm=new short[count];int noise=0x13579b;for(int i=0;i<count;i++){noise=noise*1103515245+12345;double envelope=Math.exp(-i/48.0),snap=Math.sin(2*Math.PI*1850*i/rate)*.72+(((noise>>>16)&255)/127.5-1)*.28;pcm[i]=(short)(11500*envelope*snap);}try{AudioTrack track=new AudioTrack.Builder().setAudioAttributes(new AudioAttributes.Builder().setUsage(AudioAttributes.USAGE_MEDIA).setContentType(AudioAttributes.CONTENT_TYPE_SONIFICATION).build()).setAudioFormat(new AudioFormat.Builder().setEncoding(AudioFormat.ENCODING_PCM_16BIT).setSampleRate(rate).setChannelMask(AudioFormat.CHANNEL_OUT_MONO).build()).setTransferMode(AudioTrack.MODE_STATIC).setBufferSizeInBytes(count*2).build();track.write(pcm,0,count);track.play();main.postDelayed(()->{try{track.stop();}catch(Exception ignored){}track.release();},100);}catch(Exception ignored){}}
    private void updateStreamStats(){
        if(streamStats==null)return;if(paused){if(playWhenReady)streamStats.setText("STARTING\n"+videoWidth+"×"+videoHeight+" · "+lastCodec);else setPausedStats();return;}if(directDecoder!=null){streamStats.setText(Math.round(directDecoder.kbps())+" kbps · "+String.format(Locale.US,"%.1f",directDecoder.fps())+" FPS\n"+videoWidth+"×"+videoHeight+" · "+lastCodec);return;}if(player==null)return;
        IMedia.VideoTrack track=player.getCurrentVideoTrack();IMedia media=player.getMedia();IMedia.Stats live=media==null?null:media.getStats();String codec="H264";int width=videoWidth,height=videoHeight;float fps=0;
        if(track!=null){String raw=track.codec==null?"":track.codec.toUpperCase(Locale.US);codec=raw.contains("H265")||raw.contains("HEVC")?"H265":raw.contains("H264")||raw.contains("AVC")?"H264":raw.length()>8?raw.substring(0,8):raw;lastCodec=codec;if(catalogVideoWidth<=0&&track.width>0&&track.height>0){width=track.width;height=track.height;videoWidth=width;videoHeight=height;}if(track.frameRateDen>0)fps=(float)track.frameRateNum/track.frameRateDen;}
        if(live!=null){long now=System.currentTimeMillis(),elapsed=lastStatsMs>0?now-lastStatsMs:0;int trafficBytes=Math.max(live.readBytes,live.demuxReadBytes);if(elapsed>0&&live.displayedPictures>=lastPictures){float measured=(live.displayedPictures-lastPictures)*1000f/elapsed;smoothedFps=smoothedFps<0?measured:smoothedFps*.9f+measured*.1f;}float measuredKbps=0;if(elapsed>0&&lastReadBytes>=0&&trafficBytes>=lastReadBytes)measuredKbps=(trafficBytes-lastReadBytes)*8f/elapsed;if(measuredKbps<=0){float nativeRate=Math.max(live.inputBitrate,live.demuxBitrate);if(nativeRate>0)measuredKbps=nativeRate*8000f;}if(measuredKbps>0)smoothedKbps=smoothedKbps<0?measuredKbps:smoothedKbps*.8f+measuredKbps*.2f;lastPictures=live.displayedPictures;lastReadBytes=trafficBytes;lastStatsMs=now;}
        if(camera.corridor&&width<height){int swap=width;width=height;height=swap;}if(smoothedFps>=0)fps=smoothedFps;
        String bitrate=smoothedKbps<0?"—":Integer.toString(Math.round(smoothedKbps)),first=bitrate+" kbps · "+String.format(Locale.US,"%.1f",fps)+" FPS",resolution=width+"×"+height,value=first+"\n"+resolution+" · "+codec;android.text.SpannableString styled=new android.text.SpannableString(value);styled.setSpan(new android.text.style.RelativeSizeSpan(1.2f),0,bitrate.length(),android.text.Spanned.SPAN_EXCLUSIVE_EXCLUSIVE);int resolutionStart=first.length()+1;styled.setSpan(new android.text.style.RelativeSizeSpan(1.24f),resolutionStart,resolutionStart+resolution.length(),android.text.Spanned.SPAN_EXCLUSIVE_EXCLUSIVE);styled.setSpan(new android.text.style.RelativeSizeSpan(.72f),value.length()-codec.length(),value.length(),android.text.Spanned.SPAN_EXCLUSIVE_EXCLUSIVE);streamStats.setText(styled);
    }
    private void setPausedStats(){if(streamStats==null)return;String detail=showingBestView?"BEST VIEW":videoWidth+"×"+videoHeight+" · "+lastCodec;streamStats.setText("PAUSED\n"+detail);lastStatsMs=0;lastPictures=0;lastReadBytes=-1;smoothedFps=smoothedKbps=-1f;}
    private void updatePlaybackClock(){if(playbackClock==null)return;String current=time(actualTime),value="PLAYBACK\n"+current;android.text.SpannableString styled=new android.text.SpannableString(value);styled.setSpan(new android.text.style.RelativeSizeSpan(.72f),0,8,android.text.Spanned.SPAN_EXCLUSIVE_EXCLUSIVE);styled.setSpan(new android.text.style.RelativeSizeSpan(1.35f),9,value.length(),android.text.Spanned.SPAN_EXCLUSIVE_EXCLUSIVE);playbackClock.setText(styled);}

    private void replayFailed(){if(destroyed)return;if(pendingPausedSeek!=Long.MIN_VALUE){pausedSeekInFlight=false;stopReplay(false);main.removeCallbacks(dispatchPausedSeek);main.post(dispatchPausedSeek);return;}if(!strictEventTarget&&!fallbackTried&&fallbackTime>0&&fallbackTime!=actualTime){fallbackTried=true;stopReplay(false);decodeToNearestKeyframe(fallbackTime,false);return;}pausedSeekInFlight=false;paused=true;playWhenReady=false;freezeAtTarget=false;if(playPause!=null){playPause.setEnabled(true);playPause.setText("▶");}setPausedStats();showError("Archive stream unavailable at "+time(actualTime));}
    private void showError(String error){overlay.status=error==null?"ARCHIVE UNAVAILABLE":error;overlay.invalidate();}

    private void seek(long target){queuePausedSeek(target);}
    private void seekTimeline(long target){queuePausedSeek(nearestAiTime(target));}
    private void queuePausedSeek(long target){if(!paused)updateActualTimeFromPlayer();holdCurrentFrame();paused=true;playWhenReady=false;activePlaybackEnd=0;autoAdvancePending=false;if(playPause!=null){playPause.setText("▶");playPause.setEnabled(false);}setPausedStats();updatePlaybackClock();pendingPausedSeek=target;main.removeCallbacks(dispatchPausedSeek);main.postDelayed(dispatchPausedSeek,90);}
    private long nearestAiTime(long target){long dayStart=ArchiveTimeline.dayStart(target),best;synchronized(profileEvents){best=ProfileGRepository.nearestActivityTime(profileEvents,target,dayStart,dayStart+ArchiveTimeline.DAY);}Log.i("FelicityReplay","Timeline snap · requested="+time(target)+" · nearest ONVIF activity/keyframe request="+time(best));return best;}
    private void prepareSeek(long target){syncTime=target;strictEventTarget=false;fallbackTried=false;ThreeEyeState.Event nearest=nearest(archiveEvents,target);fallbackTime=nearest==null?target:parseUtc(nearest.capturedAt);ArchiveSession.set(prefs,target,System.currentTimeMillis());ensureProfileTimeline(overlay.visibleStart(),overlay.visibleEnd());}

    private void playFromTarget(long target){prepareSeek(target);decodeToNearestKeyframe(target,true);}

    private void togglePlayback(){if(freezeAtTarget){playWhenReady=true;playPause.setText("Ⅱ");return;}if(paused){strictEventTarget=false;startRealtime(resumeStartTime>0?resumeStartTime:syncTime);return;}updateActualTimeFromPlayer();activePlaybackEnd=0;autoAdvancePending=false;enterStaticPause(actualTime,false);}
    private void jumpEvent(int direction){long reference=freezeTargetTime>0?freezeTargetTime:actualTime,best=direction<0?Long.MIN_VALUE:Long.MAX_VALUE;synchronized(profileEvents){for(ProfileGClient.SearchEvent event:profileEvents){if(isMotion(event.type))continue;long at=event.time;if(direction<0&&at<reference-500&&at>best)best=at;if(direction>0&&at>reference+500&&at<best)best=at;}}if(best!=Long.MIN_VALUE&&best!=Long.MAX_VALUE)seek(best);}
    private void showCalendar(){Set<Long> days=new HashSet<>();Calendar calendar=Calendar.getInstance();for(ThreeEyeState.Event event:archiveEvents)if(!isMotion(event.objectClass))addDay(days,calendar,parseUtc(event.capturedAt));for(ProfileGClient.SearchEvent event:profileEvents)if(!isMotion(event.type))addDay(days,calendar,event.time);if(days.isEmpty()){showError("No indexed recording days");return;}ArrayList<Long> sorted=new ArrayList<>(days);Collections.sort(sorted,Collections.reverseOrder());LinearLayout body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(18,10,18,10);TextView note=new TextView(this);note.setText("Days with Profile G / AI records · "+camera.name);note.setTextColor(Color.LTGRAY);note.setTextSize(13);body.addView(note);GridLayout grid=new GridLayout(this);grid.setColumnCount(4);body.addView(grid);SimpleDateFormat label=new SimpleDateFormat("EEE\ndd MMM",Locale.getDefault());final AlertDialog[] dialog=new AlertDialog[1];for(Long day:sorted){Button choice=button(label.format(new Date(day)));choice.setTextSize(12);GridLayout.LayoutParams p=new GridLayout.LayoutParams();p.width=0;p.height=64;p.columnSpec=GridLayout.spec(GridLayout.UNDEFINED,1,1f);p.setMargins(4,4,4,4);grid.addView(choice,p);choice.setOnClickListener(v->{Calendar current=Calendar.getInstance();current.setTimeInMillis(actualTime>0?actualTime:System.currentTimeMillis());Calendar selected=Calendar.getInstance();selected.setTimeInMillis(day);selected.set(Calendar.HOUR_OF_DAY,current.get(Calendar.HOUR_OF_DAY));selected.set(Calendar.MINUTE,current.get(Calendar.MINUTE));selected.set(Calendar.SECOND,current.get(Calendar.SECOND));ThreeEyeState.Event nearest=nearestOnDay(archiveEvents,selected.getTimeInMillis(),day);if(dialog[0]!=null)dialog[0].dismiss();seekTimeline(nearest==null?selected.getTimeInMillis():parseUtc(nearest.capturedAt));});}dialog[0]=new AlertDialog.Builder(this).setTitle("Recording calendar").setView(body).setNegativeButton("Close",null).create();dialog[0].show();}
    private static void addDay(Set<Long> days,Calendar calendar,long at){if(at<=0)return;calendar.setTimeInMillis(at);calendar.set(Calendar.HOUR_OF_DAY,0);calendar.set(Calendar.MINUTE,0);calendar.set(Calendar.SECOND,0);calendar.set(Calendar.MILLISECOND,0);days.add(calendar.getTimeInMillis());}
    private static ThreeEyeState.Event nearestOnDay(List<ThreeEyeState.Event> events,long target,long day){ThreeEyeState.Event result=null;long distance=Long.MAX_VALUE;for(ThreeEyeState.Event event:events){long at=parseUtc(event.capturedAt);Calendar c=Calendar.getInstance();c.setTimeInMillis(at);c.set(Calendar.HOUR_OF_DAY,0);c.set(Calendar.MINUTE,0);c.set(Calendar.SECOND,0);c.set(Calendar.MILLISECOND,0);if(c.getTimeInMillis()!=day)continue;long next=Math.abs(at-target);if(next<distance){distance=next;result=event;}}return result;}

    private void pickCamera(){startActivityForResult(new Intent(this,CameraPickerActivity.class),CameraPickerActivity.REQUEST);}
    @Override protected void onActivityResult(int request,int result,Intent data){super.onActivityResult(request,result,data);if(request!=CameraPickerActivity.REQUEST||result!=RESULT_OK||data==null)return;CameraCatalog.Camera selected=CameraCatalog.find(prefs,data.getStringExtra("camera_name"));ArchiveSession.touch(prefs,System.currentTimeMillis());CameraCatalog.select(prefs,selected);startActivity(new Intent(this,ArchiveActivity.class).putExtra("camera",selected.name).putExtra("camera_switch",true).putExtra("back_label",backLabel));finish();}
    private void openLive(){startActivity(new Intent(this,CameraActivity.class).putExtra("manual",true).putExtra("camera_id",camera.id).putExtra("camera_name",camera.name).putExtra("back_label","‹ ARCHIVE"));}
    private void openEvents(){startActivity(new Intent(this,EventsActivity.class).putExtra("camera_name",camera.name).putExtra("back_label","‹ ARCHIVE"));}

    private void stopReplay(boolean releaseEngine){main.removeCallbacks(firstFrameTimeout);if(directSession!=null){directSession.close();directSession=null;}if(directDecoder!=null){directDecoder.close();directDecoder=null;}if(decoderSurface!=null){decoderSurface.release();decoderSurface=null;}if(player!=null){try{player.setEventListener(null);player.stop();player.getVLCVout().detachViews();}catch(Exception ignored){}player.release();player=null;}realtimeSession=false;if(releaseEngine&&vlc!=null){vlc.release();vlc=null;}if(proxy!=null){proxy.close();proxy=null;}if(metadataSession!=null){metadataSession.stop();metadataSession=null;}}
    @Override protected void onDestroy(){destroyed=true;replayRequest++;main.removeCallbacksAndMessages(null);network.shutdownNow();metadataNetwork.shutdownNow();stopReplay(true);super.onDestroy();}

    private static ThreeEyeState.Event nearest(List<ThreeEyeState.Event> events,long target){ThreeEyeState.Event result=null;long distance=Long.MAX_VALUE;for(ThreeEyeState.Event event:events){long value=parseUtc(event.capturedAt),next=Math.abs(value-target);if(value>0&&next<distance){distance=next;result=event;}}return result;}
    private static List<ThreeEyeState.Event> withoutMotion(List<ThreeEyeState.Event> events){ArrayList<ThreeEyeState.Event> result=new ArrayList<>();for(ThreeEyeState.Event event:events)if(!isMotion(event.objectClass))result.add(event);return result;}
    private static boolean isMotion(String value){return value!=null&&value.toLowerCase(Locale.US).contains("motion");}
    static long parseUtc(String iso){return ArchiveTimeline.parseIso8601(iso);}
    private static String time(long value){return value<=0?"—":new SimpleDateFormat("HH:mm:ss",Locale.getDefault()).format(new Date(value));}

    private final class ArchiveOverlay extends View {
        private final Paint p=new Paint(3);private final GestureDetector videoDoubleTap;private float scale=1,downX,pinchStartSpan,pinchStartZoom,pinchFocusX,pinchFocusY,lastX,lastY;private long viewportCenter,downViewportCenter,visibleSpan=ArchiveTimeline.DAY;private double millisPerPixel=90_000;private boolean dragging,moved,videoGesture,pinching;private VelocityTracker velocity;String status="";
        ArchiveOverlay(Context context){super(context);videoDoubleTap=new GestureDetector(context,new GestureDetector.SimpleOnGestureListener(){@Override public boolean onDown(MotionEvent event){return true;}@Override public boolean onDoubleTap(MotionEvent event){float y=event.getY()-videoContainer.getTop();if(zoom>1.05f){zoom=1f;panX=panY=0;applyVideoZoom();}else zoomAt(event.getX(),y,2.5f);return true;}});}
        long dayStart(long value){return ArchiveTimeline.dayStart(value);}
        void showAdaptive(long value,int eventCount){visibleSpan=ArchiveTimeline.adaptiveSpan(eventCount);viewportCenter=visibleSpan>=ArchiveTimeline.DAY?dayStart(value)+ArchiveTimeline.DAY/2:value;millisPerPixel=visibleSpan/(double)Math.max(1,getWidth()>0?getWidth():960);invalidate();}
        void reveal(long value){long start=visibleStart(),end=visibleEnd();if(value<start||value>end){viewportCenter=value;ensureProfileTimeline(visibleStart(),visibleEnd());}invalidate();}
        long visibleStart(){return timeAt(0);}
        long visibleEnd(){return timeAt(Math.max(1,getWidth()));}
        private void ensureViewport(long value){if(viewportCenter<=0)showAdaptive(value,eventCountOnDay(archiveEvents,value));}
        private long timeAt(float x){return viewportCenter+(long)((x-getWidth()/2f)*millisPerPixel);}
        private float xAt(long value){return getWidth()/2f+(float)((value-viewportCenter)/millisPerPixel);}
        @Override protected void onSizeChanged(int width,int height,int oldWidth,int oldHeight){super.onSizeChanged(width,height,oldWidth,oldHeight);if(width>0)millisPerPixel=visibleSpan/(double)width;}
        @Override protected void onDraw(Canvas canvas){super.onDraw(canvas);scale=Math.min(getWidth()/960f,getHeight()/480f);ensureViewport(actualTime);p.setColor(Color.rgb(14,48,43));canvas.drawRect(0,0,getWidth(),64*scale,p);String chip=compactStatus();if(!chip.isEmpty()){p.setTypeface(android.graphics.Typeface.DEFAULT_BOLD);p.setTextSize(10*scale);float width=Math.min(getWidth()-24*scale,p.measureText(chip)+20*scale);p.setColor(0x99000000);canvas.drawRoundRect(new RectF(12*scale,76*scale,12*scale+width,102*scale),7*scale,7*scale,p);label(canvas,chip,22*scale,95,10,Color.rgb(150,190,184),Paint.Align.LEFT,true);}drawTimeline(canvas,actualTime);}
        private String compactStatus(){if(status==null||status.isEmpty()||status.startsWith("BEST VIEW")||status.startsWith("ARCHIVE ·"))return "";if(status.equals("LOADING EVENTS"))return "LOADING";return status.replace(" · ","  ");}
        private void drawTimeline(Canvas canvas,long playhead){float top=getHeight()-80*scale,base=top+36*scale;p.setStyle(Paint.Style.FILL);p.setColor(0xff101615);canvas.drawRect(0,top,getWidth(),getHeight(),p);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(.8f*scale);p.setColor(0xff596460);canvas.drawLine(0,base,getWidth(),base,p);double desiredMajor=Math.max(60_000,millisPerPixel*120*scale);long[] steps={60_000,5*60_000,15*60_000,30*60_000,60*60_000,2*60*60_000,3*60*60_000,6*60*60_000};long major=steps[steps.length-1];for(long step:steps)if(step>=desiredMajor){major=step;break;}long minor=Math.max(60_000,major/4),first=ArchiveTimeline.ceil(timeAt(0),minor);for(long at=first;at<=timeAt(getWidth());at+=minor){float x=xAt(at);boolean isMajor=ArchiveTimeline.isMajor(at,major);float length=(isMajor?23:11)*scale;p.setStrokeWidth((isMajor?1.35f:.7f)*scale);p.setColor(isMajor?0xffaeb8b4:0xff69736f);canvas.drawLine(x,base-length/2,x,base+length/2,p);if(isMajor)label(canvas,shortTime(at),x,getHeight()/scale-7,10,0xffb8c1bd,Paint.Align.CENTER,false);}p.setStyle(Paint.Style.FILL);synchronized(profileEvents){for(ProfileGClient.SearchEvent event:profileEvents)drawEvent(canvas,event.time,event.endTime,event.type,top,base);}float marker=xAt(playhead);if(marker>=0&&marker<=getWidth()){p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(1.6f*scale);p.setColor(Color.WHITE);canvas.drawLine(marker,top-5*scale,marker,getHeight()-3*scale,p);p.setStyle(Paint.Style.FILL);canvas.drawCircle(marker,top-5*scale,3*scale,p);}}
        private void drawEvent(Canvas canvas,long at,long end,String type,float top,float base){int color=eventColor(type);if(color==Color.TRANSPARENT)return;float x=xAt(at),right=end>at?xAt(end):x;if(right<-6||x>getWidth()+6)return;p.setColor(color);float half=1.5f*scale;canvas.drawRoundRect(new RectF(x-half,top+3*scale,Math.max(x+half,right),base-3*scale),half,half,p);}
        private int eventColor(String value){String type=value==null?"":value.toLowerCase(Locale.US);if(type.contains("ring"))return 0xffffb02e;if(type.contains("motion"))return Color.TRANSPARENT;if(type.contains("person")||type.contains("human"))return 0xff2fa9e8;if(type.contains("animal")||type.contains("pet"))return 0xff8247f5;if(type.contains("vehicle")||type.contains("car"))return 0xff7acb2f;if(type.contains("face"))return 0xff21b7d5;return Color.TRANSPARENT;}
        @Override public boolean onTouchEvent(MotionEvent event){float timelineTop=getHeight()-90*scale;if(event.getActionMasked()==MotionEvent.ACTION_DOWN){videoGesture=event.getY()>=videoContainer.getTop()&&event.getY()<timelineTop;if(videoGesture){if(scroller!=null)scroller.forceFinished(true);pinching=false;moved=false;lastX=event.getX();lastY=event.getY();velocity=VelocityTracker.obtain();velocity.addMovement(event);videoDoubleTap.onTouchEvent(event);return true;}downX=event.getX();downViewportCenter=viewportCenter;moved=false;dragging=event.getY()>=timelineTop;invalidate();return true;}if(videoGesture){videoDoubleTap.onTouchEvent(event);return handleVideoTouch(event);}if(!dragging)return true;if(event.getActionMasked()==MotionEvent.ACTION_MOVE){float delta=downX-event.getX();if(Math.abs(delta)>6*scale)moved=true;viewportCenter=downViewportCenter+(long)(delta*millisPerPixel);ensureProfileTimeline(visibleStart(),visibleEnd());invalidate();return true;}if(event.getActionMasked()==MotionEvent.ACTION_UP){long selected=moved?viewportCenter:timeAt(event.getX());dragging=false;ensureProfileTimeline(visibleStart(),visibleEnd());if(!moved)playTimelineClick();seekTimeline(selected);return true;}if(event.getActionMasked()==MotionEvent.ACTION_CANCEL){dragging=false;invalidate();return true;}return true;}
        private boolean handleVideoTouch(MotionEvent event){switch(event.getActionMasked()){case MotionEvent.ACTION_POINTER_DOWN:if(event.getPointerCount()>=2){pinching=true;moved=true;float[] geometry=pinchGeometry(event);pinchStartSpan=Math.max(1f,geometry[0]);pinchFocusX=geometry[1];pinchFocusY=geometry[2];pinchStartZoom=zoom;if(velocity!=null)velocity.clear();}return true;case MotionEvent.ACTION_MOVE:if(pinching&&event.getPointerCount()>=2){float[] geometry=pinchGeometry(event);float next=Math.max(1f,Math.min(6f,pinchStartZoom*geometry[0]/pinchStartSpan));if(next<1.035f)next=1f;panX+=geometry[1]-pinchFocusX;panY+=geometry[2]-pinchFocusY;pinchFocusX=geometry[1];pinchFocusY=geometry[2];zoomAt(pinchFocusX,pinchFocusY,next);}else if(!pinching&&event.getPointerCount()==1&&zoom>1f){float x=event.getX(),y=event.getY();panX+=(x-lastX)*zoom;panY+=(y-lastY)*zoom;lastX=x;lastY=y;moved=true;applyVideoZoom();if(velocity!=null)velocity.addMovement(event);}return true;case MotionEvent.ACTION_POINTER_UP:if(pinching){pinching=false;if(zoom<1.08f){zoom=1f;panX=panY=0;applyVideoZoom();}int remaining=event.getActionIndex()==0?1:0;if(remaining<event.getPointerCount()){lastX=event.getX(remaining);lastY=event.getY(remaining);}}return true;case MotionEvent.ACTION_UP:if(zoom<1.08f){zoom=1f;panX=panY=0;applyVideoZoom();}fling();recycleVelocity();videoGesture=false;return true;case MotionEvent.ACTION_CANCEL:recycleVelocity();pinching=false;videoGesture=false;return true;default:return true;}}
        private float[] pinchGeometry(MotionEvent event){float ax=event.getX(0),ay=event.getY(0)-videoContainer.getTop(),bx=event.getX(1),by=event.getY(1)-videoContainer.getTop(),dx=bx-ax,dy=by-ay;return new float[]{(float)Math.hypot(dx,dy),(ax+bx)/2f,(ay+by)/2f};}
        private void fling(){if(velocity==null||pinching||zoom<=1f)return;velocity.computeCurrentVelocity(1000);float[] bounds=panBounds();scroller.fling(Math.round(panX),Math.round(panY),Math.round(velocity.getXVelocity()*zoom),Math.round(velocity.getYVelocity()*zoom),Math.round(-bounds[0]),Math.round(bounds[0]),Math.round(-bounds[1]),Math.round(bounds[1]));postOnAnimation(ArchiveActivity.this::continueFling);}
        private void recycleVelocity(){if(velocity!=null){velocity.recycle();velocity=null;}}
        private void label(Canvas canvas,String value,float x,float y,float size,int color,Paint.Align align,boolean bold){p.setTypeface(bold?android.graphics.Typeface.DEFAULT_BOLD:android.graphics.Typeface.DEFAULT);p.setTextSize(size*scale);p.setTextAlign(align);p.setColor(color);canvas.drawText(value,x,y*scale,p);}
    }
    private static int eventCountOnDay(List<ThreeEyeState.Event> events,long target){long start=ArchiveTimeline.dayStart(target),end=start+ArchiveTimeline.DAY;int count=0;for(ThreeEyeState.Event event:events){if(isMotion(event.objectClass))continue;long at=parseUtc(event.capturedAt);if(at>=start&&at<end)count++;}return count;}
    private static String shortTime(long value){String full=time(value);return full.length()>=5?full.substring(0,5):full;}
}
