package io.github.okiyashko1337.felicitydashboard;

import android.media.AudioFormat;
import android.media.AudioRecord;
import android.media.MediaRecorder;
import android.os.Build;
import android.util.Log;
import java.io.BufferedInputStream;
import java.io.BufferedOutputStream;
import java.io.ByteArrayOutputStream;
import java.io.InputStream;
import java.io.OutputStream;
import java.net.DatagramPacket;
import java.net.DatagramSocket;
import java.net.InetAddress;
import java.net.Socket;
import java.net.URI;
import java.security.MessageDigest;
import java.security.SecureRandom;
import java.util.Locale;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

final class BackchannelSession {
    private static final String TAG="FelicityAudio";
    interface Listener { void onStarted(); void onError(String message); }
    private final String base,host,user,password;private final int port;private final Listener listener;private volatile boolean stopped;private Socket rtsp;private DatagramSocket rtp;private InputStream input;private OutputStream output;private AudioRecord recorder;private Thread thread,recordThread;
    BackchannelSession(android.content.Context context,String streamUri,String user,String password,Listener listener){this.user=user;this.password=password;this.listener=listener;URI parsed=URI.create(streamUri);host=parsed.getHost();port=parsed.getPort()>0?parsed.getPort():554;base="rtsp://"+host+(parsed.getPort()>0?":"+parsed.getPort():"")+parsed.getRawPath();}
    void start(){thread=new Thread(this::run,"onvif-talk-rtsp");thread.start();}
    void stop(){stopped=true;close();}
    private void run(){try{rtsp=new Socket(host,port);rtsp.setSoTimeout(7000);input=new BufferedInputStream(rtsp.getInputStream());output=new BufferedOutputStream(rtsp.getOutputStream());Response first=request("DESCRIBE",base,1,"Accept: application/sdp\r\nRequire: www.onvif.org/ver20/backchannel\r\n",null);String challenge=first.auth;if(challenge==null)throw new Exception("Digest challenge missing");Response described=request("DESCRIBE",base,2,"Accept: application/sdp\r\nRequire: www.onvif.org/ver20/backchannel\r\n",digest(challenge,"DESCRIBE",base));if(described.code!=200)throw new Exception("DESCRIBE "+described.code);String track=backchannelTrack(described.body);Log.i(TAG,"Backchannel SDP accepted · track="+track.substring(track.lastIndexOf('/')+1));
            do{rtp=new DatagramSocket(0);}while(rtp.getLocalPort()==65535);int clientPort=rtp.getLocalPort();Response setup=request("SETUP",track,3,"Transport: RTP/AVP;unicast;client_port="+clientPort+"-"+(clientPort+1)+"\r\nRequire: www.onvif.org/ver20/backchannel\r\n",digest(challenge,"SETUP",track));if(setup.code!=200)throw new Exception("SETUP "+setup.code);String session=match(setup.head,"Session:\\s*([^;\\r\\n]+)"),serverPort=match(setup.head,"server_port=(\\d+)");if(session==null||serverPort==null)throw new Exception("Backchannel transport missing");Response play=request("PLAY",base,4,"Session: "+session+"\r\nRange: npt=0.000-\r\nRequire: www.onvif.org/ver20/backchannel\r\n",digest(challenge,"PLAY",base));if(play.code!=200)throw new Exception("PLAY "+play.code);Log.i(TAG,"Backchannel RTSP playing · UDP "+serverPort);startAudio(Integer.parseInt(serverPort));Thread.sleep(500);if(!stopped)listener.onStarted();int cseq=5;while(!stopped){Thread.sleep(1000);request("GET_PARAMETER",base,cseq++,"Session: "+session+"\r\n",digest(challenge,"GET_PARAMETER",base));}}
        catch(Exception e){if(!stopped){Log.e(TAG,"Backchannel failed",e);listener.onError(e.getMessage()==null?e.getClass().getSimpleName():e.getMessage());}}finally{close();}}
    private void startAudio(int serverPort)throws Exception{int min=AudioRecord.getMinBufferSize(16000,AudioFormat.CHANNEL_IN_MONO,AudioFormat.ENCODING_PCM_16BIT),source=isDragon()?MediaRecorder.AudioSource.MIC:MediaRecorder.AudioSource.VOICE_COMMUNICATION;Log.i(TAG,"Opening microphone · source="+(source==MediaRecorder.AudioSource.MIC?"MIC":"VOICE_COMMUNICATION")+" · model="+Build.MODEL);recorder=new AudioRecord(source,16000,AudioFormat.CHANNEL_IN_MONO,AudioFormat.ENCODING_PCM_16BIT,Math.max(min,4096));if(recorder.getState()!=AudioRecord.STATE_INITIALIZED)throw new Exception("Microphone unavailable");rtp.connect(InetAddress.getByName(host),serverPort);recorder.startRecording();recordThread=new Thread(()->sendAudio(serverPort),"onvif-talk-mic");recordThread.start();}
    private void sendAudio(int serverPort){G722Encoder encoder=new G722Encoder();short[] pcm=new short[320];byte[] encoded=new byte[160],packet=new byte[172];SecureRandom random=new SecureRandom();int sequence=random.nextInt(65536),timestamp=random.nextInt(),ssrc=random.nextInt(),filled=0;long packets=0,levelEnergy=0;int levelSamples=0,levelPeak=0;try{while(!stopped){int count=recorder.read(pcm,filled,pcm.length-filled);if(count<0)throw new Exception("AudioRecord "+count);if(count==0)continue;for(int i=filled;i<filled+count;i++){int sample=pcm[i],absolute=sample==Short.MIN_VALUE?32768:Math.abs(sample);levelPeak=Math.max(levelPeak,absolute);levelEnergy+=(long)sample*sample;levelSamples++;}filled+=count;if(filled<pcm.length)continue;int payload=encoder.encode(pcm,0,filled,encoded);packet[0]=(byte)0x80;packet[1]=(byte)(9|(packets==0?0x80:0));put16(packet,2,sequence++);put32(packet,4,timestamp);put32(packet,8,ssrc);System.arraycopy(encoded,0,packet,12,payload);rtp.send(new DatagramPacket(packet,12+payload));timestamp+=payload;filled=0;packets++;if(packets==1)Log.i(TAG,"First microphone G.722 RTP packet sent · "+payload+" B");if(packets%50==0&&levelSamples>0){double rms=Math.sqrt(levelEnergy/(double)levelSamples),db=rms<1?-96:20*Math.log10(rms/32768.0);Log.i(TAG,"Microphone level · "+String.format(Locale.US,"%.1f",db)+" dBFS · peak="+levelPeak);levelEnergy=0;levelSamples=0;levelPeak=0;}}}catch(Exception error){if(!stopped)Log.e(TAG,"Microphone RTP failed",error);}finally{Log.i(TAG,"Microphone RTP stopped · packets="+packets+" · destination="+serverPort);}}
    private static boolean isDragon(){return "TM15".equalsIgnoreCase(Build.MODEL)||Build.HARDWARE.toLowerCase(Locale.US).contains("sun50");}
    private static void put16(byte[] out,int offset,int value){out[offset]=(byte)(value>>8);out[offset+1]=(byte)value;}
    private static void put32(byte[] out,int offset,int value){out[offset]=(byte)(value>>24);out[offset+1]=(byte)(value>>16);out[offset+2]=(byte)(value>>8);out[offset+3]=(byte)value;}
    private Response request(String method,String uri,int cseq,String extra,String auth)throws Exception{StringBuilder b=new StringBuilder(method+" "+uri+" RTSP/1.0\r\nCSeq: "+cseq+"\r\nUser-Agent: Felicity-Android/0.15\r\n");if(auth!=null)b.append("Authorization: ").append(auth).append("\r\n");b.append(extra).append("\r\n");output.write(b.toString().getBytes("ISO-8859-1"));output.flush();ByteArrayOutputStream head=new ByteArrayOutputStream();int state=0,v;while((v=input.read())>=0){head.write(v);state=(state==0&&v=='\r')?1:(state==1&&v=='\n')?2:(state==2&&v=='\r')?3:(state==3&&v=='\n')?4:0;if(state==4)break;}String h=head.toString("ISO-8859-1");String length=match(h,"Content-Length:\\s*(\\d+)");int n=length==null?0:Integer.parseInt(length);byte[] body=new byte[n];for(int off=0;off<n;){int got=input.read(body,off,n-off);if(got<0)break;off+=got;}String status=match(h,"RTSP/1.0\\s+(\\d+)");return new Response(status==null?0:Integer.parseInt(status),h,new String(body,"ISO-8859-1"),match(h,"WWW-Authenticate:\\s*Digest\\s+([^\\r\\n]+)"));}
    private String backchannelTrack(String s)throws Exception{String control=null;boolean audio=false,send=false;for(String raw:s.replace("\r","").split("\n")){String line=raw.trim();if(line.startsWith("m=")){if(audio&&send&&control!=null)return resolve(control);audio=line.startsWith("m=audio");send=false;control=null;}else if(audio&&line.equals("a=sendonly"))send=true;else if(audio&&line.startsWith("a=control:"))control=line.substring(10).trim();}if(audio&&send&&control!=null)return resolve(control);throw new Exception("ONVIF sendonly audio track missing");}
    private String resolve(String control){if(control.startsWith("rtsp://"))return control;if(control.startsWith("/"))return "rtsp://"+host+(port==554?"":":"+port)+control;return base+(base.endsWith("/")?"":"/")+control;}
    private String digest(String challenge,String method,String address)throws Exception{String realm=param(challenge,"realm"),nonce=param(challenge,"nonce"),ha1=md5(user+":"+realm+":"+password),ha2=md5(method+":"+address),response=md5(ha1+":"+nonce+":"+ha2);return "Digest username=\""+user+"\", realm=\""+realm+"\", nonce=\""+nonce+"\", uri=\""+address+"\", response=\""+response+"\"";}
    private synchronized void close(){if(recorder!=null){try{recorder.stop();}catch(Exception ignored){}recorder.release();recorder=null;}if(rtp!=null){rtp.close();rtp=null;}if(recordThread!=null){recordThread.interrupt();recordThread=null;}try{if(rtsp!=null)rtsp.close();}catch(Exception ignored){}rtsp=null;}
    private static String param(String s,String name){Matcher m=Pattern.compile(name+"=\"([^\"]+)\"",Pattern.CASE_INSENSITIVE).matcher(s);return m.find()?m.group(1):"";}private static String match(String s,String re){Matcher m=Pattern.compile(re,Pattern.CASE_INSENSITIVE).matcher(s);return m.find()?m.group(1):null;}private static String md5(String s)throws Exception{byte[] d=MessageDigest.getInstance("MD5").digest(s.getBytes("ISO-8859-1"));StringBuilder b=new StringBuilder();for(byte v:d)b.append(String.format(Locale.US,"%02x",v&255));return b.toString();}
    private static final class Response{final int code;final String head,body,auth;Response(int code,String head,String body,String auth){this.code=code;this.head=head;this.body=body;this.auth=auth;}}
}
