package io.github.okiyashko1337.felicitydashboard;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.content.SharedPreferences;
import android.graphics.Bitmap;
import android.graphics.BitmapFactory;
import android.graphics.Canvas;
import android.graphics.Color;
import android.graphics.Matrix;
import android.graphics.Paint;
import android.graphics.RectF;
import android.os.Bundle;
import android.view.MotionEvent;
import android.view.VelocityTracker;
import android.view.View;
import android.view.ViewConfiguration;
import android.view.WindowManager;
import android.widget.OverScroller;
import java.io.File;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/** Static camera wall. Preview files are written only after real playback renders a frame. */
public final class CameraPickerActivity extends Activity {
    static final int REQUEST=80;
    private SharedPreferences prefs;private List<CameraCatalog.Camera> cameras;private final Map<String,Bitmap> previews=new HashMap<>();private PickerView view;private boolean closeCameraOnBack;private String selectedId="",backLabel="‹ LIVE";

    @Override protected void onCreate(Bundle saved){
        super.onCreate(saved);getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);DeviceUi.apply(this);prefs=getSharedPreferences("felicity",MODE_PRIVATE);
        String requestedBack=getIntent().getStringExtra("back_label");if(requestedBack!=null&&!requestedBack.isEmpty())backLabel=requestedBack;closeCameraOnBack=getIntent().getBooleanExtra("close_camera_on_back",false);cameras=CameraCatalog.load(prefs);selectedId=CameraCatalog.selected(prefs).id;
        for(CameraCatalog.Camera camera:cameras){Bitmap local=decodePreview(new File(getFilesDir(),"camera-preview-"+camera.id+".jpg"));if(local!=null&&isUseful(local))previews.put(camera.id,prepareLocal(local,camera));else if(local!=null)local.recycle();}
        view=new PickerView(this);setContentView(view);
    }

    private void choose(CameraCatalog.Camera camera){int legacyPage=view.legacyPage();prefs.edit().putFloat("camera_picker_scroll",view.scroll).putInt("camera_picker_page",legacyPage).apply();Intent result=new Intent().putExtra("camera_id",camera.id).putExtra("camera_name",camera.name).putExtra("camera_page",legacyPage);setResult(RESULT_OK,result);finish();}
    private static Bitmap decodePreview(File file){String path=file.getAbsolutePath();BitmapFactory.Options bounds=new BitmapFactory.Options();bounds.inJustDecodeBounds=true;BitmapFactory.decodeFile(path,bounds);if(bounds.outWidth<1||bounds.outHeight<1)return null;int sample=1;while(bounds.outWidth/sample>720||bounds.outHeight/sample>480)sample*=2;BitmapFactory.Options options=new BitmapFactory.Options();options.inSampleSize=sample;options.inPreferredConfig=Bitmap.Config.RGB_565;return BitmapFactory.decodeFile(path,options);}
    private static Bitmap prepareLocal(Bitmap source,CameraCatalog.Camera camera){Bitmap trimmed=trimBlackBars(source);if(trimmed!=source)source.recycle();int rotation=CameraCatalog.displayRotation(camera);if(rotation==0)return trimmed;Matrix matrix=new Matrix();matrix.postRotate(rotation);Bitmap result=Bitmap.createBitmap(trimmed,0,0,trimmed.getWidth(),trimmed.getHeight(),matrix,true);if(result!=trimmed)trimmed.recycle();return result;}
    private static Bitmap trimBlackBars(Bitmap source){int width=source.getWidth(),height=source.getHeight();if(width<20||height<20)return source;int left=0,right=width-1,top=0,bottom=height-1;while(left<width/2&&!columnHasImage(source,left))left++;while(right>width/2&&!columnHasImage(source,right))right--;while(top<height/2&&!rowHasImage(source,top))top++;while(bottom>height/2&&!rowHasImage(source,bottom))bottom--;int leftBar=left,rightBar=width-1-right,topBar=top,bottomBar=height-1-bottom;boolean vertical=leftBar+rightBar>width/8&&Math.abs(leftBar-rightBar)<width/6&&right-left>width/8;boolean horizontal=topBar+bottomBar>height/8&&Math.abs(topBar-bottomBar)<height/6&&bottom-top>height/8;if(!vertical){left=0;right=width-1;}if(!horizontal){top=0;bottom=height-1;}if(left==0&&right==width-1&&top==0&&bottom==height-1)return source;return Bitmap.createBitmap(source,left,top,right-left+1,bottom-top+1);}
    private static boolean columnHasImage(Bitmap bitmap,int x){int hits=0,needed=Math.max(2,bitmap.getHeight()/60);for(int y=0;y<bitmap.getHeight();y+=3){int c=bitmap.getPixel(x,y);if(Color.red(c)+Color.green(c)+Color.blue(c)>45&&++hits>=needed)return true;}return false;}
    private static boolean rowHasImage(Bitmap bitmap,int y){int hits=0,needed=Math.max(2,bitmap.getWidth()/60);for(int x=0;x<bitmap.getWidth();x+=3){int c=bitmap.getPixel(x,y);if(Color.red(c)+Color.green(c)+Color.blue(c)>45&&++hits>=needed)return true;}return false;}
    private static boolean isUseful(Bitmap bitmap){if(bitmap==null||bitmap.getWidth()<2||bitmap.getHeight()<2)return false;int max=0;for(int y=1;y<=4;y++)for(int x=1;x<=6;x++){int c=bitmap.getPixel(x*bitmap.getWidth()/7,y*bitmap.getHeight()/5);max=Math.max(max,(Color.red(c)*3+Color.green(c)*6+Color.blue(c))/10);}return max>12;}
    @Override protected void onDestroy(){for(Bitmap bitmap:previews.values())if(bitmap!=null&&!bitmap.isRecycled())bitmap.recycle();previews.clear();super.onDestroy();}

    private final class PickerView extends View {
        final Paint p=new Paint(3);final RectF r=new RectF();final OverScroller scroller;final int touchSlop,minFling;float scale=1,scroll,downX,downY,downScroll;int pressed=-1,downTarget=-1;boolean dragging,flinging,previewsSized;VelocityTracker velocity;
        final int bg=Color.rgb(7,17,15),header=Color.rgb(14,48,43),card=Color.rgb(13,39,35),cyan=Color.rgb(89,222,209),text=Color.rgb(232,248,244),muted=Color.rgb(150,190,184);
        PickerView(Context context){super(context);setBackgroundColor(bg);scroller=new OverScroller(context);ViewConfiguration config=ViewConfiguration.get(context);touchSlop=config.getScaledTouchSlop();minFling=config.getScaledMinimumFlingVelocity();scroll=prefs.getFloat("camera_picker_scroll",0);}
        @Override protected void onSizeChanged(int width,int height,int oldWidth,int oldHeight){super.onSizeChanged(width,height,oldWidth,oldHeight);scale=Math.min(width/960f,height/480f);if(!previewsSized&&width>0&&height>0){previewsSized=true;int targetWidth=Math.max(1,Math.round(cardWidth()-6*scale)),targetHeight=Math.max(1,Math.round(cardHeight()-41*scale));Paint bitmapPaint=new Paint(Paint.ANTI_ALIAS_FLAG|Paint.FILTER_BITMAP_FLAG);for(Map.Entry<String,Bitmap> entry:previews.entrySet()){Bitmap source=entry.getValue();if(source==null)continue;Bitmap ready=Bitmap.createBitmap(targetWidth,targetHeight,Bitmap.Config.RGB_565);Canvas canvas=new Canvas(ready);canvas.drawColor(Color.BLACK);RectF bounds=new RectF(0,0,targetWidth,targetHeight);canvas.drawBitmap(source,null,fit(source,bounds),bitmapPaint);source.recycle();entry.setValue(ready);}}}
        private float top(){return 76*scale;}private float gap(){return 10*scale;}private float pad(){return 16*scale;}private float cardWidth(){return (getWidth()-2*pad()-2*gap())/3f;}private float cardHeight(){return Math.max(150*scale,(getHeight()-top()-26*scale-gap())/2f);}private int rows(){return Math.max(1,(cameras.size()+2)/3);}private float maxScroll(){return Math.max(0,rows()*(cardHeight()+gap())-gap()-(getHeight()-top()-12*scale));}
        private void clamp(){scroll=Math.max(0,Math.min(maxScroll(),scroll));}
        @Override protected void onDraw(Canvas c){super.onDraw(c);scale=Math.min(getWidth()/960f,getHeight()/480f);clamp();float pad=pad(),gap=gap(),top=top(),cw=cardWidth(),ch=cardHeight();c.save();c.clipRect(0,top,getWidth(),getHeight());c.translate(0,-scroll);int first=Math.max(0,(int)(scroll/(ch+gap))-1),last=Math.min(rows()-1,(int)((scroll+getHeight()-top)/(ch+gap))+1);for(int row=first;row<=last;row++)for(int col=0;col<3;col++){int index=row*3+col;if(index>=cameras.size())break;CameraCatalog.Camera camera=cameras.get(index);float x=pad+col*(cw+gap),y=top+row*(ch+gap),inset=pressed==index?4*scale:0;r.set(x+inset,y+inset,x+cw-inset,y+ch-inset);p.setColor(card);c.drawRoundRect(r,14*scale,14*scale,p);RectF image=new RectF(r.left+3*scale,r.top+3*scale,r.right-3*scale,r.bottom-38*scale);p.setColor(Color.BLACK);c.drawRect(image,p);Bitmap preview=previews.get(camera.id);if(preview!=null){if(inset==0&&preview.getWidth()==Math.round(image.width())&&preview.getHeight()==Math.round(image.height()))c.drawBitmap(preview,image.left,image.top,p);else c.drawBitmap(preview,null,fit(preview,image),p);}else label(c,"NO PREVIEW",image.centerX()/scale,image.centerY()/scale+4,13,muted,Paint.Align.CENTER,true);p.setColor(0xdd112925);c.drawRect(r.left,r.bottom-38*scale,r.right,r.bottom,p);label(c,camera.name,r.centerX()/scale,r.bottom/scale-13,14,selectedId.equals(camera.id)?cyan:text,Paint.Align.CENTER,true);}c.restore();p.setColor(header);c.drawRect(0,0,getWidth(),64*scale,p);p.setColor(pressed==-2?0xff1c4e46:0xff123d37);c.drawRoundRect(new RectF(8*scale,7*scale,136*scale,57*scale),8*scale,8*scale,p);label(c,backLabel,72,40,12,text,Paint.Align.CENTER,true);label(c,"SELECT CAMERA",getWidth()/2f/scale,40,21,cyan,Paint.Align.CENTER,true);label(c,cameras.size()+" CAMERAS",getWidth()/scale-18,40,11,muted,Paint.Align.RIGHT,true);if(maxScroll()>0){float trackTop=72*scale,trackBottom=getHeight()-8*scale,thumb=Math.max(34*scale,(trackBottom-trackTop)*(getHeight()-top)/(getHeight()-top+maxScroll())),thumbY=trackTop+(trackBottom-trackTop-thumb)*(scroll/maxScroll());p.setColor(0xff315f58);c.drawRoundRect(new RectF(getWidth()-7*scale,thumbY,getWidth()-3*scale,thumbY+thumb),3*scale,3*scale,p);}}
        @Override public boolean onTouchEvent(MotionEvent event){switch(event.getActionMasked()){case MotionEvent.ACTION_DOWN:scroller.forceFinished(true);flinging=false;downX=event.getX();downY=event.getY();downScroll=scroll;downTarget=pressed=hit(downX,downY);dragging=false;velocity=VelocityTracker.obtain();velocity.addMovement(event);postInvalidateOnAnimation();return true;case MotionEvent.ACTION_MOVE:if(velocity!=null)velocity.addMovement(event);float dx=event.getX()-downX,dy=event.getY()-downY;if(!dragging&&Math.hypot(dx,dy)>touchSlop){dragging=true;pressed=-1;}if(dragging){scroll=downScroll-dy*1.28f;clamp();postInvalidateOnAnimation();}return true;case MotionEvent.ACTION_POINTER_DOWN:dragging=true;pressed=-1;postInvalidateOnAnimation();return true;case MotionEvent.ACTION_UP:if(velocity!=null){velocity.addMovement(event);velocity.computeCurrentVelocity(1000);float vy=velocity.getYVelocity();if(dragging&&Math.abs(vy)>=minFling){scroller.fling(0,Math.round(scroll),0,Math.round(-vy*1.55f),0,0,0,Math.round(maxScroll()));flinging=true;postInvalidateOnAnimation();}velocity.recycle();velocity=null;}int target=hit(event.getX(),event.getY());pressed=-1;if(!dragging&&target==downTarget){if(target==-2){if(closeCameraOnBack)setResult(RESULT_CANCELED,new Intent().putExtra("close_camera",true));finish();return true;}if(target>=0&&target<cameras.size()){choose(cameras.get(target));return true;}}if(!flinging)savePosition();postInvalidateOnAnimation();return true;case MotionEvent.ACTION_CANCEL:if(velocity!=null){velocity.recycle();velocity=null;}pressed=-1;dragging=false;savePosition();postInvalidateOnAnimation();return true;default:return true;}}
        @Override public void computeScroll(){if(scroller.computeScrollOffset()){scroll=scroller.getCurrY();postInvalidateOnAnimation();}else if(flinging){flinging=false;savePosition();}}
        private void savePosition(){prefs.edit().putFloat("camera_picker_scroll",scroll).putInt("camera_picker_page",legacyPage()).apply();}
        int legacyPage(){float group=Math.max(1,2*(cardHeight()+gap()));return Math.max(0,Math.round(scroll/group));}
        private int hit(float x,float y){if(y<64*scale&&x<144*scale)return -2;float top=top(),pad=pad(),gap=gap(),cw=cardWidth(),ch=cardHeight(),contentY=y+scroll;if(y<top||x<pad||x>getWidth()-pad)return -1;int col=(int)((x-pad)/(cw+gap)),row=(int)((contentY-top)/(ch+gap));if(col<0||col>=3||row<0)return -1;float localX=(x-pad)-col*(cw+gap),localY=(contentY-top)-row*(ch+gap);int index=row*3+col;return localX<=cw&&localY<=ch&&index<cameras.size()?index:-1;}
        private RectF fit(Bitmap bitmap,RectF bounds){float aspect=bitmap.getWidth()/(float)Math.max(1,bitmap.getHeight()),w=bounds.width(),h=w/aspect;if(h>bounds.height()){h=bounds.height();w=h*aspect;}return new RectF(bounds.centerX()-w/2,bounds.centerY()-h/2,bounds.centerX()+w/2,bounds.centerY()+h/2);}
        private void label(Canvas c,String value,float x,float y,float size,int color,Paint.Align align,boolean bold){p.setTypeface(bold?android.graphics.Typeface.DEFAULT_BOLD:android.graphics.Typeface.DEFAULT);p.setTextSize(size*scale);p.setTextAlign(align);p.setColor(color);c.drawText(value,x*scale,y*scale,p);}
    }
}
