package io.github.okiyashko1337.felicitydashboard;

import android.app.Activity;
import android.app.AlertDialog;
import android.content.Context;
import android.content.Intent;
import android.content.SharedPreferences;
import android.graphics.Bitmap;
import android.graphics.Canvas;
import android.graphics.Color;
import android.graphics.Paint;
import android.graphics.RectF;
import android.os.Bundle;
import android.os.Handler;
import android.os.Looper;
import android.view.MotionEvent;
import android.view.VelocityTracker;
import android.view.View;
import android.view.ViewConfiguration;
import android.view.WindowManager;
import android.widget.EditText;
import android.widget.LinearLayout;
import android.widget.OverScroller;
import android.widget.Toast;
import java.io.File;
import java.io.FileOutputStream;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import java.util.HashMap;
import java.util.Map;
import java.util.TimeZone;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

public final class EventsActivity extends Activity {
    private final ThreeEyeState state=new ThreeEyeState();
    private final ThreeEyeClient client=new ThreeEyeClient(state);
    private final ExecutorService network=Executors.newSingleThreadExecutor();
    private final Handler main=new Handler(Looper.getMainLooper());
    private EventsView view;
    private SharedPreferences prefs;
    private String doorbell="";
    private String backLabel="‹ ENERGY";
    private boolean showAllCameras;

    @Override protected void onCreate(Bundle saved){super.onCreate(saved);getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);immersive();prefs=getSharedPreferences("felicity",MODE_PRIVATE);String requested=getIntent().getStringExtra("camera_name");doorbell=requested==null||requested.isEmpty()?prefs.getString("threeeye_doorbell_camera",""):requested;String requestedBack=getIntent().getStringExtra("back_label");if(requestedBack!=null&&!requestedBack.isEmpty())backLabel=requestedBack;String user=prefs.getString("threeeye_user",prefs.getString("ajax_user",""));String password=prefs.getString("threeeye_password",prefs.getString("ajax_password",""));client.configure(prefs.getString("threeeye_base_url",state.baseUrl),user,password);view=new EventsView(this);setContentView(view);reload();}
    @Override protected void onResume(){super.onResume();immersive();}
    @Override protected void onDestroy(){network.shutdownNow();if(view!=null)view.release();super.onDestroy();}
    private void immersive(){DeviceUi.apply(this);}

    private void reload(){state.camera=showAllCameras||doorbell.isEmpty()?"ALL":doorbell;EventFilters.apply(state,eventMask());state.status="LOADING";view.invalidate();network.execute(()->client.load((ok,error)->main.post(()->{if(ok){chooseDoorbell();synchronized(state.cameras){CameraCatalog.save(prefs,state.channels);}}view.invalidate();})));}
    private void chooseDoorbell(){if(!doorbell.isEmpty())return;List<String> cameras; synchronized(state.cameras){cameras=new ArrayList<>(state.cameras);}for(String camera:cameras){String n=camera.toLowerCase(Locale.US);if(n.contains("door")||n.contains("bell")||n.contains("ajax")||n.contains("entrance")||n.contains("front")){doorbell=camera;break;}}if(doorbell.isEmpty()&&cameras.size()==1)doorbell=cameras.get(0);if(!doorbell.isEmpty())prefs.edit().putString("threeeye_doorbell_camera",doorbell).apply();}
    private List<ThreeEyeState.Event> events(){List<ThreeEyeState.Event> all=state.snapshot();ArrayList<ThreeEyeState.Event> result=new ArrayList<>();for(ThreeEyeState.Event event:all)if(event.thumbnail!=null&&(showAllCameras||doorbell.isEmpty()||doorbell.equalsIgnoreCase(event.camera)))result.add(event);return result;}
    private void pickCamera(){startActivityForResult(new Intent(this,CameraPickerActivity.class),CameraPickerActivity.REQUEST);}
    private int eventMask(){return showAllCameras?prefs.getInt("event_filter_all_cameras",EventFilters.ALL):EventFilters.get(prefs,CameraCatalog.find(prefs,doorbell));}
    private void toggleScope(){showAllCameras=!showAllCameras;view.resetScroll();reload();}
    private void toggleFilter(int flag){int mask=eventMask(),next=mask^flag;if(next==0){Toast.makeText(this,"Keep at least one event type",Toast.LENGTH_SHORT).show();return;}if(showAllCameras)prefs.edit().putInt("event_filter_all_cameras",next).apply();else EventFilters.set(prefs,CameraCatalog.find(prefs,doorbell),next);EventFilters.apply(state,next);view.resetScroll();reload();}
    @Override protected void onActivityResult(int request,int result,Intent data){super.onActivityResult(request,result,data);if(request!=CameraPickerActivity.REQUEST||result!=RESULT_OK||data==null)return;doorbell=data.getStringExtra("camera_name");if(doorbell==null)return;showAllCameras=false;view.resetScroll();prefs.edit().putString("threeeye_doorbell_camera",doorbell).apply();CameraCatalog.select(prefs,CameraCatalog.find(prefs,doorbell));reload();}
    private void configureThreeEye(){LinearLayout fields=new LinearLayout(this);fields.setOrientation(LinearLayout.VERTICAL);int pad=(int)(18*getResources().getDisplayMetrics().density);fields.setPadding(pad,0,pad,0);EditText url=new EditText(this);url.setHint("3ye API URL");url.setSingleLine(true);url.setText(prefs.getString("threeeye_base_url",state.baseUrl));fields.addView(url);EditText user=new EditText(this);user.setHint("3ye user");user.setSingleLine(true);user.setText(prefs.getString("threeeye_user",""));fields.addView(user);EditText password=new EditText(this);password.setHint("3ye password");password.setSingleLine(true);password.setInputType(android.text.InputType.TYPE_CLASS_TEXT|android.text.InputType.TYPE_TEXT_VARIATION_PASSWORD);fields.addView(password);new AlertDialog.Builder(this).setTitle("3ye events").setMessage("Credentials stay in Android private preferences.").setView(fields).setNegativeButton("Cancel",null).setPositiveButton("Save",(dialog,which)->{String base=url.getText().toString().trim(),u=user.getText().toString().trim(),pw=password.getText().toString();if(base.isEmpty())return;if(!base.startsWith("http://")&&!base.startsWith("https://"))base="http://"+base;if(pw.isEmpty())pw=prefs.getString("threeeye_password","");prefs.edit().putString("threeeye_base_url",base).putString("threeeye_user",u).putString("threeeye_password",pw).apply();client.configure(base,u,pw);reload();}).show();}
    private void openLive(){CameraCatalog.Camera camera=CameraCatalog.find(prefs,doorbell);CameraCatalog.select(prefs,camera);startActivity(new Intent(this,CameraActivity.class).putExtra("manual",true).putExtra("trigger","EVENTS_LIVE").putExtra("back_label","‹ EVENTS").putExtra("camera_id",camera.id).putExtra("camera_name",camera.name));}
    private void openEvent(ThreeEyeState.Event event){long eventTime=ArchiveActivity.parseUtc(event.capturedAt);if(eventTime>0)ArchiveSession.set(prefs,eventTime,System.currentTimeMillis());CameraCatalog.select(prefs,CameraCatalog.find(prefs,event.camera));state.status="OPENING ARCHIVE";view.invalidate();network.execute(()->client.loadSelectedImage(event,(ok,error)->{String path="";if(ok&&event.image!=null){File file=new File(getCacheDir(),"best-view-"+event.trackId+".jpg");try(FileOutputStream out=new FileOutputStream(file)){event.image.compress(Bitmap.CompressFormat.JPEG,92,out);path=file.getAbsolutePath();}catch(Exception ignored){}}String imagePath=path;main.post(()->{state.status="LIVE";view.invalidate();startActivity(new Intent(this,ArchiveActivity.class).putExtra("best_view_path",imagePath).putExtra("captured_at_utc",event.capturedAt).putExtra("camera",event.camera).putExtra("track_id",event.trackId).putExtra("from_event",true).putExtra("back_label","‹ EVENTS"));});}));}

    private final class EventsView extends View {
        private final Paint p=new Paint(3);private final RectF r=new RectF();private final OverScroller scroller;private final int touchSlop,minFling;private final Map<Long,Bitmap> prepared=new HashMap<>();private int pressed=-1,downTarget=-1,drawnCount;private float scale=1,scroll,downX,downY,downScroll;private boolean dragging,flinging;private VelocityTracker velocity;
        private final int bg=Color.rgb(7,17,15),header=Color.rgb(14,48,43),card=Color.rgb(13,39,35),cyan=Color.rgb(89,222,209),text=Color.rgb(232,248,244),muted=Color.rgb(150,190,184),amber=Color.rgb(255,184,103);
        EventsView(Context c){super(c);setBackgroundColor(bg);scroller=new OverScroller(c);ViewConfiguration config=ViewConfiguration.get(c);touchSlop=config.getScaledTouchSlop();minFling=config.getScaledMinimumFlingVelocity();}
        private float top(){return 76*scale;}private float gap(){return 10*scale;}private float pad(){return 16*scale;}private float cardWidth(){return (getWidth()-2*pad()-2*gap())/3f;}private float cardHeight(){return Math.max(150*scale,(getHeight()-top()-12*scale-gap())/2f);}private int rows(int count){return Math.max(1,(count+2)/3);}private float maxScroll(int count){return Math.max(0,rows(count)*(cardHeight()+gap())-gap()-(getHeight()-top()-8*scale));}private void clamp(int count){scroll=Math.max(0,Math.min(maxScroll(count),scroll));}
        void resetScroll(){scroll=0;scroller.forceFinished(true);flinging=false;releasePrepared();postInvalidateOnAnimation();}void release(){releasePrepared();}private void releasePrepared(){for(Bitmap bitmap:prepared.values())if(bitmap!=null&&!bitmap.isRecycled())bitmap.recycle();prepared.clear();}
        @Override protected void onDraw(Canvas c){super.onDraw(c);scale=Math.min(getWidth()/960f,getHeight()/480f);List<ThreeEyeState.Event> items=events();drawnCount=items.size();clamp(drawnCount);float pad=pad(),gap=gap(),top=top(),cw=cardWidth(),ch=cardHeight();c.save();c.clipRect(0,top,getWidth(),getHeight());c.translate(0,-scroll);int first=Math.max(0,(int)(scroll/(ch+gap))-1),last=Math.min(rows(drawnCount)-1,(int)((scroll+getHeight()-top)/(ch+gap))+1);for(int row=first;row<=last;row++)for(int col=0;col<3;col++){int index=row*3+col;if(index>=drawnCount)break;ThreeEyeState.Event event=items.get(index);float x=pad+col*(cw+gap),y=top+row*(ch+gap),inset=pressed==index?4*scale:0;r.set(x+inset,y+inset,x+cw-inset,y+ch-inset);p.setColor(card);c.drawRoundRect(r,14*scale,14*scale,p);RectF image=new RectF(r.left+3*scale,r.top+3*scale,r.right-3*scale,r.bottom-49*scale);p.setColor(Color.BLACK);c.drawRect(image,p);Bitmap b=prepared(event,Math.max(1,Math.round(cw-6*scale)),Math.max(1,Math.round(ch-52*scale)));if(b!=null){if(inset==0&&b.getWidth()==Math.round(image.width())&&b.getHeight()==Math.round(image.height()))c.drawBitmap(b,image.left,image.top,p);else c.drawBitmap(b,null,fitInside(b,image),p);}p.setColor(0xd9112925);c.drawRect(r.left,r.bottom-50*scale,r.right,r.bottom,p);label(c,eventTime(event.capturedAt),(r.left+10*scale)/scale,r.bottom/scale-27,14,text,Paint.Align.LEFT,true);label(c,event.objectClass.toUpperCase(Locale.US),(r.right-10*scale)/scale,r.bottom/scale-27,11,cyan,Paint.Align.RIGHT,true);label(c,event.camera,(r.left+10*scale)/scale,r.bottom/scale-9,10,muted,Paint.Align.LEFT,false);}c.restore();drawHeader(c);if(items.isEmpty()){label(c,"OFFLINE".equals(state.status)?state.error:"No matching events with images",getWidth()/2f/scale,getHeight()/2f/scale,20,"OFFLINE".equals(state.status)?amber:muted,Paint.Align.CENTER,false);if("OFFLINE".equals(state.status))label(c,"Tap to configure 3ye",getWidth()/2f/scale,getHeight()/2f/scale+28,14,cyan,Paint.Align.CENTER,true);}else if(!"LIVE".equals(state.status))label(c,state.status,getWidth()/2f/scale,92,14,muted,Paint.Align.CENTER,true);float max=maxScroll(drawnCount);if(max>0){float trackTop=72*scale,trackBottom=getHeight()-8*scale,thumb=Math.max(34*scale,(trackBottom-trackTop)*(getHeight()-top)/(getHeight()-top+max)),thumbY=trackTop+(trackBottom-trackTop-thumb)*(scroll/max);p.setColor(0xff315f58);c.drawRoundRect(new RectF(getWidth()-7*scale,thumbY,getWidth()-3*scale,thumbY+thumb),3*scale,3*scale,p);}}
        private void drawHeader(Canvas c){p.setColor(header);c.drawRect(0,0,getWidth(),64*scale,p);p.setColor(pressed==-2?0xff1c4e46:0xff123d37);c.drawRoundRect(new RectF(8*scale,7*scale,128*scale,57*scale),8*scale,8*scale,p);label(c,backLabel,68,40,12,text,Paint.Align.CENTER,true);label(c,"3YE · "+shortName(showAllCameras?"ALL":doorbell.isEmpty()?"EVENTS":doorbell,10),138,40,14,cyan,Paint.Align.LEFT,true);p.setColor(pressed==-3?0xff24675d:0xff174a43);c.drawRoundRect(new RectF(288*scale,8*scale,406*scale,56*scale),10*scale,10*scale,p);label(c,showAllCameras?"ALL CAMERAS":"THIS CAMERA",347,39,10,text,Paint.Align.CENTER,true);int mask=eventMask();drawFilter(c,"PERSON",EventFilters.PERSON,412,mask);drawFilter(c,"VEHICLE",EventFilters.VEHICLE,548,mask);drawFilter(c,"ANIMAL",EventFilters.ANIMAL,684,mask);drawFilter(c,"FACE",EventFilters.FACE,820,mask);}
        private Bitmap prepared(ThreeEyeState.Event event,int width,int height){Bitmap ready=prepared.get(event.trackId);if(ready!=null&&!ready.isRecycled()&&ready.getWidth()==width&&ready.getHeight()==height)return ready;Bitmap source=event.thumbnail;if(source==null)return null;if(ready!=null&&!ready.isRecycled())ready.recycle();ready=Bitmap.createBitmap(width,height,Bitmap.Config.RGB_565);Canvas canvas=new Canvas(ready);canvas.drawColor(Color.BLACK);Paint imagePaint=new Paint(Paint.ANTI_ALIAS_FLAG|Paint.FILTER_BITMAP_FLAG);canvas.drawBitmap(source,null,fitInside(source,new RectF(0,0,width,height)),imagePaint);prepared.put(event.trackId,ready);return ready;}
        @Override public boolean onTouchEvent(MotionEvent e){switch(e.getActionMasked()){case MotionEvent.ACTION_DOWN:scroller.forceFinished(true);flinging=false;downX=e.getX();downY=e.getY();downScroll=scroll;downTarget=pressed=hit(downX,downY);dragging=false;velocity=VelocityTracker.obtain();velocity.addMovement(e);postInvalidateOnAnimation();return true;case MotionEvent.ACTION_MOVE:if(velocity!=null)velocity.addMovement(e);float dx=e.getX()-downX,dy=e.getY()-downY;if(!dragging&&Math.hypot(dx,dy)>touchSlop){dragging=true;pressed=-1;}if(dragging){scroll=downScroll-dy*1.28f;clamp(drawnCount);postInvalidateOnAnimation();}return true;case MotionEvent.ACTION_POINTER_DOWN:dragging=true;pressed=-1;postInvalidateOnAnimation();return true;case MotionEvent.ACTION_UP:if(velocity!=null){velocity.addMovement(e);velocity.computeCurrentVelocity(1000);float vy=velocity.getYVelocity();if(dragging&&Math.abs(vy)>=minFling){scroller.fling(0,Math.round(scroll),0,Math.round(-vy*1.55f),0,0,0,Math.round(maxScroll(drawnCount)));flinging=true;postInvalidateOnAnimation();}velocity.recycle();velocity=null;}int target=hit(e.getX(),e.getY());pressed=-1;if(!dragging&&target==downTarget){if(target==-2){finish();return true;}if(target==-3){toggleScope();return true;}if(target<=-10&&target>=-13){int[] flags={EventFilters.PERSON,EventFilters.VEHICLE,EventFilters.ANIMAL,EventFilters.FACE};toggleFilter(flags[-10-target]);return true;}if("OFFLINE".equals(state.status)){configureThreeEye();return true;}List<ThreeEyeState.Event> items=events();if(target>=0&&target<items.size())openEvent(items.get(target));}postInvalidateOnAnimation();return true;case MotionEvent.ACTION_CANCEL:if(velocity!=null){velocity.recycle();velocity=null;}pressed=-1;dragging=false;postInvalidateOnAnimation();return true;default:return true;}}
        @Override public void computeScroll(){if(scroller.computeScrollOffset()){scroll=scroller.getCurrY();postInvalidateOnAnimation();}else flinging=false;}
        private int hit(float x,float y){if(y<64*scale){if(x<132*scale)return -2;if(x>=288*scale&&x<408*scale)return -3;int[] starts={412,548,684,820};for(int i=0;i<starts.length;i++)if(x>=starts[i]*scale&&x<(starts[i]+128)*scale)return -10-i;return -1;}float top=top(),pad=pad(),gap=gap(),cw=cardWidth(),ch=cardHeight(),contentY=y+scroll;if(y<top||x<pad||x>getWidth()-pad)return -1;int col=(int)((x-pad)/(cw+gap)),row=(int)((contentY-top)/(ch+gap));if(col<0||col>=3||row<0)return -1;float localX=(x-pad)-col*(cw+gap),localY=(contentY-top)-row*(ch+gap);int index=row*3+col;return localX<=cw&&localY<=ch&&index<drawnCount?index:-1;}
        private void drawFilter(Canvas c,String value,int flag,float left,int mask){int index=flag==EventFilters.PERSON?0:flag==EventFilters.VEHICLE?1:flag==EventFilters.ANIMAL?2:3;boolean enabled=(mask&flag)!=0;p.setColor(pressed==-10-index?0xff24675d:enabled?0xff174a43:0xff0b2723);c.drawRoundRect(new RectF(left*scale,8*scale,(left+128)*scale,56*scale),10*scale,10*scale,p);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(1.5f*scale);p.setColor(enabled?cyan:0xff52756f);c.drawRoundRect(new RectF(left*scale,8*scale,(left+128)*scale,56*scale),10*scale,10*scale,p);p.setStyle(Paint.Style.FILL);label(c,value,left+64,39,12,enabled?text:muted,Paint.Align.CENTER,true);}
        private RectF fitInside(Bitmap bitmap,RectF bounds){float ratio=Math.min(bounds.width()/bitmap.getWidth(),bounds.height()/bitmap.getHeight()),w=bitmap.getWidth()*ratio,h=bitmap.getHeight()*ratio;return new RectF(bounds.centerX()-w/2f,bounds.centerY()-h/2f,bounds.centerX()+w/2f,bounds.centerY()+h/2f);}
        private void label(Canvas c,String value,float x,float y,float size,int color,Paint.Align align,boolean bold){p.setTypeface(bold?android.graphics.Typeface.DEFAULT_BOLD:android.graphics.Typeface.DEFAULT);p.setTextSize(size*scale);p.setTextAlign(align);p.setColor(color);c.drawText(value,x*scale,y*scale,p);}
        private String shortName(String value,int max){return value.length()<=max?value:value.substring(0,max-1)+"…";}
    }

    static String eventTime(String iso){try{SimpleDateFormat input=new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss",Locale.US);input.setTimeZone(TimeZone.getTimeZone("UTC"));Date d=input.parse(iso.length()>=19?iso.substring(0,19):iso);return new SimpleDateFormat("dd MMM  HH:mm:ss",Locale.getDefault()).format(d);}catch(Exception ignored){return iso;}}
}
