package io.github.okiyashko1337.felicitydashboard;

import android.util.Base64;
import android.util.Log;
import java.io.*;
import java.net.*;
import java.security.MessageDigest;
import java.text.SimpleDateFormat;
import java.util.*;
import java.util.concurrent.LinkedBlockingQueue;
import java.util.regex.*;

/** App-owned ONVIF Profile-G RTSP session. VLC is deliberately not involved. */
final class OnvifArchiveSession implements AutoCloseable {
    interface Listener{void onConfigured(boolean hevc,List<byte[]> csd);void onAccessUnit(byte[] data,long archiveTimeMs,long rtpTimestamp,boolean keyframe);void onError(Exception error);}
    private static final class Command{final long time;final boolean pause,close;Command(long time,boolean pause,boolean close){this.time=time;this.pause=pause;this.close=close;}}
    private static final class Response{final int code,cseq;final String head,body,auth;Response(int code,int cseq,String head,String body,String auth){this.code=code;this.cseq=cseq;this.head=head;this.body=body;this.auth=auth;}}
    private final String base,user,password;private final long initialTime;private final Listener listener;private final LinkedBlockingQueue<Command> commands=new LinkedBlockingQueue<>();private volatile boolean closed,paused,deliverMedia;private Socket socket;private BufferedInputStream input;private BufferedOutputStream output;private String challenge="",session="",track="";private int cseq;private long lastControl;private ArchiveRtpDepacketizer depacketizer;
    OnvifArchiveSession(String uri,String user,String password,long initialTime,Listener listener){this.base=uri;this.user=user;this.password=password;this.initialTime=initialTime;this.listener=listener==null?null:new Listener(){@Override public void onConfigured(boolean hevc,List<byte[]> csd){listener.onConfigured(hevc,csd);}@Override public void onAccessUnit(byte[] data,long archiveTimeMs,long rtpTimestamp,boolean keyframe){if(deliverMedia)listener.onAccessUnit(data,archiveTimeMs,rtpTimestamp,keyframe);}@Override public void onError(Exception error){listener.onError(error);}};}
    void start(){Thread thread=new Thread(this::run,"felicity-archive-rtsp");thread.setDaemon(true);thread.start();}
    void seek(long time){deliverMedia=false;commands.clear();commands.offer(new Command(time,false,false));}
    void pause(){deliverMedia=false;commands.offer(new Command(0,true,false));}
    private void run(){try{URI uri=new URI(base);Log.i("FelicityReplay","Direct RTSP connect · "+uri.getHost()+":"+(uri.getPort()>0?uri.getPort():554));socket=new Socket();socket.connect(new InetSocketAddress(uri.getHost(),uri.getPort()>0?uri.getPort():554),5000);socket.setSoTimeout(200);socket.setTcpNoDelay(true);input=new BufferedInputStream(socket.getInputStream(),256*1024);output=new BufferedOutputStream(socket.getOutputStream(),64*1024);Response first=request("DESCRIBE",base,"Accept: application/sdp\r\n",false);challenge=first.auth;if(challenge.isEmpty())throw new Exception("Archive digest challenge missing");Response described=request("DESCRIBE",base,"Accept: application/sdp\r\n",true);if(described.code!=200)throw new Exception("Archive DESCRIBE "+described.code);Sdp video=parseSdp(described.body,header(described.head,"Content-Base"));track=video.track;depacketizer=new ArchiveRtpDepacketizer(video.hevc,(data,time,rtp,key)->{if(listener!=null)listener.onAccessUnit(data,time,rtp,key);});if(listener!=null)listener.onConfigured(video.hevc,video.csd);Response setup=request("SETUP",track,"Transport: RTP/AVP/TCP;unicast;interleaved=0-1\r\nRequire: onvif-replay\r\n",true);if(setup.code!=200)throw new Exception("Archive SETUP "+setup.code);session=session(setup.head);if(session.isEmpty())throw new Exception("Archive RTSP session missing");play(initialTime);while(!closed){Command command=commands.poll();if(command!=null){if(command.close)break;if(command.pause)doPause();else doSeek(command.time);continue;}if(paused&&System.currentTimeMillis()-lastControl>4000){Response keep=request("GET_PARAMETER",base,"Session: "+session+"\r\nContent-Length: 0\r\n",true);if(keep.code>=400)request("OPTIONS",base,"Session: "+session+"\r\n",true);lastControl=System.currentTimeMillis();continue;}try{Message message=readMessage();if(message!=null&&message.rtp!=null&&message.channel==0)depacketizer.accept(message.rtp);}catch(SocketTimeoutException ignored){}}}catch(Exception error){if(!closed){Log.e("FelicityReplay","Direct RTSP failed",error);if(listener!=null)listener.onError(error);}}finally{closeSocket();}}
    private void doSeek(long time)throws Exception{if(!paused)doPause();depacketizer.reset();Response response=play(time);if(response.code!=200)throw new Exception("Archive PLAY "+response.code);}
    private void doPause()throws Exception{if(paused)return;Response response=request("PAUSE",base,"Session: "+session+"\r\n",true);if(response.code!=200)throw new Exception("Archive PAUSE "+response.code);paused=true;lastControl=System.currentTimeMillis();Log.i("FelicityReplay","Direct RTSP paused");}
    private Response play(long time)throws Exception{deliverMedia=false;Response response=request("PLAY",base,"Session: "+session+"\r\nRequire: onvif-replay\r\nRange: clock="+clock(time)+"-\r\nRate-Control: yes\r\nFrames: all\r\nImmediate: yes\r\nScale: 1.0\r\n",true);paused=false;deliverMedia=response.code==200;lastControl=System.currentTimeMillis();Log.i("FelicityReplay","Direct RTSP PLAY · "+clock(time)+" · status="+response.code);return response;}
    private Response request(String method,String uri,String extra,boolean authenticated)throws Exception{
        Response response=requestOnce(method,uri,extra,authenticated);
        // Ajax rotates the Digest nonce on a long paused archive session. Refresh it
        // in-place: the RTSP Session id and the warmed MediaCodec remain untouched.
        if(authenticated&&response.code==401&&!response.auth.isEmpty()){
            challenge=response.auth;
            Log.i("FelicityReplay","Direct RTSP digest refreshed · "+method);
            response=requestOnce(method,uri,extra,true);
        }
        return response;
    }
    private Response requestOnce(String method,String uri,String extra,boolean authenticated)throws Exception{int wanted=++cseq;Log.i("FelicityReplay","Direct RTSP request · "+method+" · cseq="+wanted);StringBuilder value=new StringBuilder(method+" "+uri+" RTSP/1.0\r\nCSeq: "+wanted+"\r\nUser-Agent: Felicity-Archive/1\r\n");if(authenticated)value.append("Authorization: ").append(digest(challenge,method,uri)).append("\r\n");value.append(extra).append("\r\n");output.write(value.toString().getBytes("ISO-8859-1"));output.flush();while(!closed){Message message=readMessage();if(message==null)continue;if(message.rtp!=null){if(deliverMedia&&message.channel==0&&depacketizer!=null)depacketizer.accept(message.rtp);continue;}if(message.response!=null&&message.response.cseq==wanted){Log.i("FelicityReplay","Direct RTSP response · "+method+" · "+message.response.code);return message.response;}}throw new EOFException();}
    private static final class Message{final int channel;final byte[] rtp;final Response response;Message(int channel,byte[] rtp,Response response){this.channel=channel;this.rtp=rtp;this.response=response;}}
    private Message readMessage()throws Exception{int first=input.read();if(first<0)throw new EOFException();if(first=='$'){int channel=input.read(),hi=input.read(),lo=input.read();if(lo<0)throw new EOFException();return new Message(channel,readFully((hi<<8)|lo),null);}byte[] header=readHeader(first);String head=new String(header,"ISO-8859-1");int length=number(header(head,"Content-Length"));String body=length>0?new String(readFully(length),"ISO-8859-1"):"";int code=number(match(head,"RTSP/1.0\\s+(\\d+)")),sequence=number(header(head,"CSeq"));String auth=header(head,"WWW-Authenticate");return new Message(-1,null,new Response(code,sequence,head,body,auth==null?"":auth));}
    private byte[] readHeader(int first)throws Exception{ByteArrayOutputStream out=new ByteArrayOutputStream();out.write(first);int state=first=='\r'?1:0;while(state<4){int value=input.read();if(value<0)throw new EOFException();out.write(value);if((state==0||state==2)&&value=='\r')state++;else if((state==1||state==3)&&value=='\n')state++;else state=value=='\r'?1:0;}return out.toByteArray();}
    private byte[] readFully(int length)throws Exception{byte[] result=new byte[length];int offset=0;while(offset<length){int count=input.read(result,offset,length-offset);if(count<0)throw new EOFException();offset+=count;}return result;}
    private static final class Sdp{final boolean hevc;final String track;final List<byte[]> csd;Sdp(boolean hevc,String track,List<byte[]> csd){this.hevc=hevc;this.track=track;this.csd=csd;}}
    private Sdp parseSdp(String body,String contentBase)throws Exception{String[] sections=body.split("(?=m=)");String video="";for(String part:sections)if(part.startsWith("m=video")){video=part;break;}if(video.isEmpty())throw new Exception("Archive video track missing");String upper=video.toUpperCase(Locale.US);boolean hevc=upper.contains("H265")||upper.contains("HEVC");String control=match(video,"(?im)^a=control:([^\\r\\n]+)");if(control==null)throw new Exception("Archive video control missing");String root=contentBase==null||contentBase.isEmpty()?base:contentBase;String address=control.startsWith("rtsp://")?control:resolve(root,control);ArrayList<byte[]> csd=new ArrayList<>();if(hevc){ByteArrayOutputStream all=new ByteArrayOutputStream();appendParameter(all,param(video,"sprop-vps"));appendParameter(all,param(video,"sprop-sps"));appendParameter(all,param(video,"sprop-pps"));if(all.size()>0)csd.add(all.toByteArray());}else{String sets=param(video,"sprop-parameter-sets");if(!sets.isEmpty())for(String set:sets.split(",")){byte[] raw=decode(set);if(raw.length>0)csd.add(annex(raw));}}Log.i("FelicityReplay","Direct SDP · "+(hevc?"H265":"H264")+" · csd="+csd.size()+" · track="+address);return new Sdp(hevc,address,csd);}
    private static void appendParameter(ByteArrayOutputStream out,String encoded){byte[] raw=decode(encoded);if(raw.length==0)return;byte[] value=annex(raw);out.write(value,0,value.length);}
    private static byte[] decode(String value){try{return value==null||value.isEmpty()?new byte[0]:Base64.decode(value.trim(),Base64.DEFAULT);}catch(Exception ignored){return new byte[0];}}
    private static byte[] annex(byte[] raw){byte[] value=new byte[raw.length+4];value[3]=1;System.arraycopy(raw,0,value,4,raw.length);return value;}
    private static String resolve(String root,String child)throws Exception{int query=root.indexOf('?');if(query>=0)root=root.substring(0,query);return root+(root.endsWith("/")?"":"/")+child;}
    private String digest(String source,String method,String uri)throws Exception{String realm=param(source,"realm"),nonce=param(source,"nonce"),qop=param(source,"qop"),opaque=param(source,"opaque"),ha1=md5(user+":"+realm+":"+password),ha2=md5(method+":"+uri),response,extra="";if(!qop.isEmpty()){String selected=qop.toLowerCase(Locale.US).contains("auth")?"auth":qop.split(",")[0].trim(),nc="00000001",cnonce=md5(Long.toHexString(System.nanoTime())).substring(0,16);response=md5(ha1+":"+nonce+":"+nc+":"+cnonce+":"+selected+":"+ha2);extra=", qop="+selected+", nc="+nc+", cnonce=\""+cnonce+"\"";}else response=md5(ha1+":"+nonce+":"+ha2);return "Digest username=\""+user+"\", realm=\""+realm+"\", nonce=\""+nonce+"\", uri=\""+uri+"\", response=\""+response+"\""+(opaque.isEmpty()?"":", opaque=\""+opaque+"\"")+extra;}
    private static String param(String input,String name){Matcher matcher=Pattern.compile("(?:^|[;, ])"+name+"\\s*=\\s*(?:\"([^\"]*)\"|([^;, \\r\\n]+))",Pattern.CASE_INSENSITIVE).matcher(input==null?"":input);return matcher.find()?(matcher.group(1)!=null?matcher.group(1):matcher.group(2)):"";}
    private static String header(String input,String name){Matcher matcher=Pattern.compile("(?im)^"+Pattern.quote(name)+"\\s*:\\s*([^\\r\\n]+)").matcher(input);return matcher.find()?matcher.group(1).trim():null;}
    private static String match(String input,String regex){Matcher matcher=Pattern.compile(regex).matcher(input);return matcher.find()?matcher.group(1).trim():null;}
    private static int number(String value){try{return value==null?0:Integer.parseInt(value.trim());}catch(Exception ignored){return 0;}}
    private static String session(String head){String value=header(head,"Session");return value==null?"":value.split(";")[0].trim();}
    private static String md5(String value)throws Exception{byte[] bytes=MessageDigest.getInstance("MD5").digest(value.getBytes("ISO-8859-1"));StringBuilder result=new StringBuilder();for(byte b:bytes)result.append(String.format(Locale.US,"%02x",b&255));return result.toString();}
    private static String clock(long time){SimpleDateFormat format=new SimpleDateFormat("yyyyMMdd'T'HHmmss'Z'",Locale.US);format.setTimeZone(TimeZone.getTimeZone("UTC"));return format.format(new Date(time));}
    @Override public void close(){closed=true;commands.offer(new Command(0,false,true));closeSocket();}
    private synchronized void closeSocket(){try{if(socket!=null)socket.close();}catch(Exception ignored){}socket=null;}
}
