plugins { id 'com.android.application' }

android {
    namespace 'io.github.okiyashko1337.felicitydashboard'
    compileSdk 32

    defaultConfig {
        applicationId 'io.github.okiyashko1337.felicitydashboard'
        minSdk 23
        targetSdk 28
        versionCode 15
        versionName '0.7.8'
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
    }
}

dependencies {
    implementation 'org.videolan.android:libvlc-all:3.5.1'
    testImplementation 'junit:junit:4.13.2'
}
